export default [
  // Greetings and common expressions
  { word: 'сәлем', english: 'hello (informal)' },
  { word: 'сәлеметсіз бе', english: 'hello (formal)' },
  { word: 'қайырлы таң', english: 'good morning' },
  { word: 'қайырлы күн', english: 'good afternoon' },
  { word: 'қайырлы кеш', english: 'good evening' },
  { word: 'қайырлы түн', english: 'good night' },
  { word: 'сау бол', english: 'goodbye (informal)' },
  { word: 'сау болыңыз', english: 'goodbye (formal)' },
  { word: 'көріскенше', english: 'see you' },
  { word: 'кездескенше', english: 'see you later' },
  { word: 'рахмет', english: 'thank you' },
  { word: 'көп рақмет', english: 'thank you very much' },
  { word: 'өтінемін', english: 'please' },
  { word: 'оқасы жоқ', english: 'you are welcome' },
  { word: 'кешіріңіз', english: 'excuse me' },
  { word: 'кешіріңізші', english: 'sorry' },
  { word: 'иә', english: 'yes' },
  { word: 'жоқ', english: 'no' },
  { word: 'мүмкін', english: 'maybe' },
  { word: 'әрине', english: 'of course' },
  { word: 'жарайды', english: 'okay' },
  { word: 'түсінемін', english: 'I understand' },
  { word: 'түсінбеймін', english: 'I do not understand' },
  { word: 'қайталаңызшы', english: 'please repeat' },
  { word: 'баяу сөйлеңізші', english: 'please speak slowly' },
  { word: 'қазақша сөйлейсіз бе', english: 'do you speak Kazakh' },
  { word: 'орысша сөйлейсіз бе', english: 'do you speak Russian' },
  { word: 'ағылшынша сөйлейсіз бе', english: 'do you speak English' },
  { word: 'менің атым', english: 'my name is' },
  { word: 'қалыңыз қалай', english: 'how are you' },
  { word: 'жақсымын', english: 'I am fine' },
  { word: 'танысқаныма қуаныштымын', english: 'nice to meet you' },
  { word: 'қайдан келдіңіз', english: 'where are you from' },
  { word: 'мен түсінбедім', english: 'I did not understand' },
  { word: 'тағы бір рет айтыңызшы', english: 'say it one more time please' },
  { word: 'көмектесіңізші', english: 'please help' },
  { word: 'маған көмек керек', english: 'I need help' },
  { word: 'бәрі жақсы', english: 'everything is good' },
  { word: 'ештеңе етпейді', english: 'it is okay / no problem' },
  { word: 'сәттілік', english: 'good luck' },
  { word: 'құтты болсын', english: 'congratulations' },
  { word: 'ас болсын', english: 'enjoy your meal' },
  { word: 'аман болыңыз', english: 'stay well' },
  { word: 'ертең көріскенше', english: 'see you tomorrow' },
  { word: 'жолыңыз болсын', english: 'have a good trip' },
  { word: 'жауап беріңізші', english: 'please answer' },
  { word: 'тыңдап тұрмын', english: 'I am listening' },
  { word: 'мен келісемін', english: 'I agree' },
  { word: 'мен келіспеймін', english: 'I disagree' },
  { word: 'маған ұнайды', english: 'I like it' },
  { word: 'маған ұнамайды', english: 'I do not like it' },
  { word: 'өте жақсы', english: 'very good' },
  { word: 'өте жаман', english: 'very bad' },
  { word: 'білмеймін', english: 'I do not know' },
  { word: 'мәселе жоқ', english: 'no problem' },
  { word: 'аздап', english: 'a little' },
  { word: 'дәл қазір', english: 'right now' },
  { word: 'кейінірек', english: 'later' },
  { word: 'бір минут', english: 'one minute' },
  { word: 'асықпаңыз', english: 'do not hurry' },
  { word: 'рақмет сізге', english: 'thank you to you' },

  // Family and people
  { word: 'отбасы', english: 'family' },
  { word: 'ата-ана', english: 'parents' },
  { word: 'ана', english: 'mother' },
  { word: 'әке', english: 'father' },
  { word: 'ата', english: 'grandfather' },
  { word: 'әже', english: 'grandmother' },
  { word: 'аға', english: 'older brother' },
  { word: 'әпке', english: 'older sister' },
  { word: 'іні', english: 'younger brother' },
  { word: 'қарындас', english: 'younger sister (for male speaker)' },
  { word: 'сіңлі', english: 'younger sister (for female speaker)' },
  { word: 'ұл', english: 'son' },
  { word: 'қыз', english: 'daughter' },
  { word: 'бала', english: 'child' },
  { word: 'нәресте', english: 'baby' },
  { word: 'немере', english: 'grandchild' },
  { word: 'күйеу', english: 'husband' },
  { word: 'әйел', english: 'wife' },
  { word: 'жұбай', english: 'spouse' },
  { word: 'ағайын', english: 'relatives' },
  { word: 'туыс', english: 'relative' },
  { word: 'дос', english: 'friend' },
  { word: 'құрбы', english: 'female friend' },
  { word: 'көрші', english: 'neighbor' },
  { word: 'қонақ', english: 'guest' },
  { word: 'ұстаз', english: 'teacher' },
  { word: 'оқушы', english: 'student (school)' },
  { word: 'студент', english: 'student (college)' },
  { word: 'дәрігер', english: 'doctor' },
  { word: 'мұғалім', english: 'teacher' },
  { word: 'инженер', english: 'engineer' },
  { word: 'сатушы', english: 'seller' },
  { word: 'жүргізуші', english: 'driver' },
  { word: 'аспаз', english: 'cook' },
  { word: 'полиция қызметкері', english: 'police officer' },
  { word: 'клиент', english: 'client' },
  { word: 'әріптес', english: 'colleague' },
  { word: 'бастық', english: 'boss' },
  { word: 'қызметкер', english: 'employee' },
  { word: 'команда', english: 'team' },

  // Numbers
  { word: 'нөл', english: 'zero' },
  { word: 'бір', english: 'one' },
  { word: 'екі', english: 'two' },
  { word: 'үш', english: 'three' },
  { word: 'төрт', english: 'four' },
  { word: 'бес', english: 'five' },
  { word: 'алты', english: 'six' },
  { word: 'жеті', english: 'seven' },
  { word: 'сегіз', english: 'eight' },
  { word: 'тоғыз', english: 'nine' },
  { word: 'он', english: 'ten' },
  { word: 'он бір', english: 'eleven' },
  { word: 'он екі', english: 'twelve' },
  { word: 'он үш', english: 'thirteen' },
  { word: 'он төрт', english: 'fourteen' },
  { word: 'он бес', english: 'fifteen' },
  { word: 'он алты', english: 'sixteen' },
  { word: 'он жеті', english: 'seventeen' },
  { word: 'он сегіз', english: 'eighteen' },
  { word: 'он тоғыз', english: 'nineteen' },
  { word: 'жиырма', english: 'twenty' },
  { word: 'жиырма бір', english: 'twenty one' },
  { word: 'жиырма екі', english: 'twenty two' },
  { word: 'жиырма үш', english: 'twenty three' },
  { word: 'жиырма төрт', english: 'twenty four' },
  { word: 'жиырма бес', english: 'twenty five' },
  { word: 'жиырма алты', english: 'twenty six' },
  { word: 'жиырма жеті', english: 'twenty seven' },
  { word: 'жиырма сегіз', english: 'twenty eight' },
  { word: 'жиырма тоғыз', english: 'twenty nine' },
  { word: 'отыз', english: 'thirty' },
  { word: 'отыз бір', english: 'thirty one' },
  { word: 'отыз екі', english: 'thirty two' },
  { word: 'отыз үш', english: 'thirty three' },
  { word: 'отыз төрт', english: 'thirty four' },
  { word: 'отыз бес', english: 'thirty five' },
  { word: 'отыз алты', english: 'thirty six' },
  { word: 'отыз жеті', english: 'thirty seven' },
  { word: 'отыз сегіз', english: 'thirty eight' },
  { word: 'отыз тоғыз', english: 'thirty nine' },
  { word: 'қырық', english: 'forty' },
  { word: 'қырық бір', english: 'forty one' },
  { word: 'қырық екі', english: 'forty two' },
  { word: 'қырық үш', english: 'forty three' },
  { word: 'қырық төрт', english: 'forty four' },
  { word: 'қырық бес', english: 'forty five' },
  { word: 'қырық алты', english: 'forty six' },
  { word: 'қырық жеті', english: 'forty seven' },
  { word: 'қырық сегіз', english: 'forty eight' },
  { word: 'қырық тоғыз', english: 'forty nine' },
  { word: 'елу', english: 'fifty' },
  { word: 'алпыс', english: 'sixty' },
  { word: 'жетпіс', english: 'seventy' },
  { word: 'сексен', english: 'eighty' },
  { word: 'тоқсан', english: 'ninety' },
  { word: 'жүз', english: 'one hundred' },
  { word: 'мың', english: 'thousand' },
  { word: 'миллион', english: 'million' },
  { word: 'бірінші', english: 'first' },
  { word: 'екінші', english: 'second' },
  { word: 'үшінші', english: 'third' },
  { word: 'төртінші', english: 'fourth' },
  { word: 'бесінші', english: 'fifth' },

  // Food and drink
  { word: 'ас', english: 'meal / food' },
  { word: 'тағам', english: 'dish / food' },
  { word: 'нан', english: 'bread' },
  { word: 'су', english: 'water' },
  { word: 'шай', english: 'tea' },
  { word: 'кофе', english: 'coffee' },
  { word: 'сүт', english: 'milk' },
  { word: 'айран', english: 'kefir drink' },
  { word: 'шырын', english: 'juice' },
  { word: 'қант', english: 'sugar' },
  { word: 'тұз', english: 'salt' },
  { word: 'бұрыш', english: 'pepper' },
  { word: 'ет', english: 'meat' },
  { word: 'сиыр еті', english: 'beef' },
  { word: 'қой еті', english: 'lamb' },
  { word: 'тауық еті', english: 'chicken meat' },
  { word: 'балық', english: 'fish' },
  { word: 'жұмыртқа', english: 'egg' },
  { word: 'күріш', english: 'rice' },
  { word: 'кеспе', english: 'noodles' },
  { word: 'ботқа', english: 'porridge' },
  { word: 'сорпа', english: 'soup' },
  { word: 'салат', english: 'salad' },
  { word: 'картоп', english: 'potato' },
  { word: 'сәбіз', english: 'carrot' },
  { word: 'пияз', english: 'onion' },
  { word: 'сарымсақ', english: 'garlic' },
  { word: 'қызанақ', english: 'tomato' },
  { word: 'қияр', english: 'cucumber' },
  { word: 'орамжапырақ', english: 'cabbage' },
  { word: 'бұрыш көкөнісі', english: 'bell pepper' },
  { word: 'алма', english: 'apple' },
  { word: 'алмұрт', english: 'pear' },
  { word: 'банан', english: 'banana' },
  { word: 'апельсин', english: 'orange' },
  { word: 'лимон', english: 'lemon' },
  { word: 'жүзім', english: 'grape' },
  { word: 'қарбыз', english: 'watermelon' },
  { word: 'қауын', english: 'melon' },
  { word: 'құлпынай', english: 'strawberry' },
  { word: 'шие', english: 'cherry' },
  { word: 'өрік', english: 'apricot' },
  { word: 'шабдалы', english: 'peach' },
  { word: 'жаңғақ', english: 'nut' },
  { word: 'ірімшік', english: 'cheese' },
  { word: 'май', english: 'butter / oil' },
  { word: 'бал', english: 'honey' },
  { word: 'тәтті', english: 'sweet (dessert)' },
  { word: 'балмұздақ', english: 'ice cream' },
  { word: 'бәліш', english: 'pie' },
  { word: 'бауырсақ', english: 'fried dough' },
  { word: 'бешбармақ', english: 'beshbarmak' },
  { word: 'палау', english: 'pilaf' },
  { word: 'дәмді', english: 'delicious' },
  { word: 'ащы', english: 'spicy' },
  { word: 'тойдым', english: 'I am full' },
  { word: 'қарным ашты', english: 'I am hungry' },
  { word: 'шөлдедім', english: 'I am thirsty' },
  { word: 'шот әкеліңізші', english: 'please bring the bill' },

  // Travel and city
  { word: 'сапар', english: 'trip' },
  { word: 'саяхат', english: 'travel' },
  { word: 'жол', english: 'road / way' },
  { word: 'көше', english: 'street' },
  { word: 'даңғыл', english: 'avenue' },
  { word: 'бұрылыс', english: 'turn' },
  { word: 'бағыт', english: 'direction' },
  { word: 'мекенжай', english: 'address' },
  { word: 'қала', english: 'city' },
  { word: 'ауыл', english: 'village' },
  { word: 'ел', english: 'country' },
  { word: 'орталық', english: 'center' },
  { word: 'әуежай', english: 'airport' },
  { word: 'вокзал', english: 'station' },
  { word: 'аялдама', english: 'stop (bus stop)' },
  { word: 'билет', english: 'ticket' },
  { word: 'ұшақ', english: 'airplane' },
  { word: 'пойыз', english: 'train' },
  { word: 'автобус', english: 'bus' },
  { word: 'такси', english: 'taxi' },
  { word: 'метро', english: 'metro' },
  { word: 'көлік', english: 'transport / vehicle' },
  { word: 'машина', english: 'car' },
  { word: 'жүргізу куәлігі', english: 'driver license' },
  { word: 'қонақүй', english: 'hotel' },
  { word: 'бөлме', english: 'room' },
  { word: 'кілт', english: 'key' },
  { word: 'бронь', english: 'reservation' },
  { word: 'төлқұжат', english: 'passport' },
  { word: 'шекара', english: 'border' },
  { word: 'кеден', english: 'customs' },
  { word: 'карта', english: 'map' },
  { word: 'касса', english: 'ticket office' },
  { word: 'жол жүру құны', english: 'fare' },
  { word: 'солға бұрылыңыз', english: 'turn left' },
  { word: 'оңға бұрылыңыз', english: 'turn right' },
  { word: 'тура жүріңіз', english: 'go straight' },
  { word: 'алыс емес', english: 'not far' },
  { word: 'жақын жерде', english: 'nearby' },
  { word: 'қайда орналасқан', english: 'where is located' },
  { word: 'дәріхана қайда', english: 'where is the pharmacy' },
  { word: 'дәретхана қайда', english: 'where is the toilet' },
  { word: 'мен жолдан адастым', english: 'I am lost' },
  { word: 'маған такси керек', english: 'I need a taxi' },
  { word: 'осы жерге апарыңыз', english: 'take me to this place' },
  { word: 'бір жаққа билет', english: 'one-way ticket' },
  { word: 'екі жаққа билет', english: 'round-trip ticket' },

  // Work and study
  { word: 'жұмыс', english: 'work' },
  { word: 'кеңсе', english: 'office' },
  { word: 'компания', english: 'company' },
  { word: 'ұйым', english: 'organization' },
  { word: 'жоба', english: 'project' },
  { word: 'тапсырма', english: 'task' },
  { word: 'міндет', english: 'duty' },
  { word: 'мақсат', english: 'goal' },
  { word: 'жоспар', english: 'plan' },
  { word: 'кесте', english: 'schedule' },
  { word: 'жиналыс', english: 'meeting' },
  { word: 'есеп', english: 'report' },
  { word: 'нәтиже', english: 'result' },
  { word: 'тәжірибе', english: 'experience' },
  { word: 'дағды', english: 'skill' },
  { word: 'білім', english: 'knowledge' },
  { word: 'сабақ', english: 'lesson' },
  { word: 'емтихан', english: 'exam' },
  { word: 'үй тапсырмасы', english: 'homework' },
  { word: 'жалақы', english: 'salary' },
  { word: 'бонус', english: 'bonus' },
  { word: 'келісімшарт', english: 'contract' },
  { word: 'қолтаңба', english: 'signature' },
  { word: 'құжат', english: 'document' },
  { word: 'хат', english: 'letter' },
  { word: 'электрондық пошта', english: 'email' },
  { word: 'қоңырау', english: 'call' },
  { word: 'сұхбат', english: 'interview' },
  { word: 'демалыс', english: 'vacation' },
  { word: 'үзіліс', english: 'break' },
  { word: 'жұмыс күні', english: 'workday' },
  { word: 'жұмыс уақыты', english: 'working hours' },
  { word: 'толық уақыт', english: 'full time' },
  { word: 'жартылай уақыт', english: 'part time' },
  { word: 'қызмет', english: 'position / service' },
  { word: 'мансап', english: 'career' },
  { word: 'кеңес', english: 'advice' },
  { word: 'шешім', english: 'decision' },
  { word: 'пікір', english: 'opinion' },
  { word: 'сұрақ', english: 'question' },
  { word: 'жауап', english: 'answer' },

  // Body and health
  { word: 'дене', english: 'body' },
  { word: 'бас', english: 'head' },
  { word: 'бет', english: 'face' },
  { word: 'көз', english: 'eye' },
  { word: 'құлақ', english: 'ear' },
  { word: 'мұрын', english: 'nose' },
  { word: 'ауыз', english: 'mouth' },
  { word: 'ерін', english: 'lip' },
  { word: 'тіс', english: 'tooth' },
  { word: 'тіл', english: 'tongue' },
  { word: 'жақ', english: 'jaw' },
  { word: 'мойын', english: 'neck' },
  { word: 'иық', english: 'shoulder' },
  { word: 'қол', english: 'arm / hand' },
  { word: 'шынтақ', english: 'elbow' },
  { word: 'білезік', english: 'wrist' },
  { word: 'алақан', english: 'palm' },
  { word: 'саусақ', english: 'finger' },
  { word: 'тырнақ', english: 'nail' },
  { word: 'кеуде', english: 'chest' },
  { word: 'арқа', english: 'back' },
  { word: 'бел', english: 'waist' },
  { word: 'іш', english: 'belly' },
  { word: 'жүрек', english: 'heart' },
  { word: 'өкпе', english: 'lung' },
  { word: 'асқазан', english: 'stomach' },
  { word: 'бауыр', english: 'liver' },
  { word: 'аяқ', english: 'leg / foot' },
  { word: 'сан', english: 'thigh' },
  { word: 'тізе', english: 'knee' },
  { word: 'балтыр', english: 'calf' },
  { word: 'өкше', english: 'heel' },
  { word: 'табан', english: 'sole' },
  { word: 'қан', english: 'blood' },
  { word: 'тері', english: 'skin' },
  { word: 'сүйек', english: 'bone' },
  { word: 'бұлшықет', english: 'muscle' },
  { word: 'ауру', english: 'illness / pain' },
  { word: 'денсаулық', english: 'health' },
  { word: 'дәрі', english: 'medicine' },
  { word: 'аурухана', english: 'hospital' },
  { word: 'емхана', english: 'clinic' },
  { word: 'жедел жәрдем', english: 'ambulance' },
  { word: 'температура', english: 'temperature' },
  { word: 'басым ауырып тұр', english: 'my head hurts' },
  { word: 'өзімді нашар сезініп тұрмын', english: 'I feel unwell' },

  // Time and calendar
  { word: 'уақыт', english: 'time' },
  { word: 'сағат', english: 'hour / clock' },
  { word: 'минут', english: 'minute' },
  { word: 'секунд', english: 'second' },
  { word: 'күн', english: 'day / sun' },
  { word: 'апта', english: 'week' },
  { word: 'ай', english: 'month' },
  { word: 'жыл', english: 'year' },
  { word: 'бүгін', english: 'today' },
  { word: 'кеше', english: 'yesterday' },
  { word: 'ертең', english: 'tomorrow' },
  { word: 'таңертең', english: 'in the morning' },
  { word: 'түсте', english: 'at noon' },
  { word: 'кешке', english: 'in the evening' },
  { word: 'түнде', english: 'at night' },
  { word: 'қазір', english: 'now' },
  { word: 'бұрын', english: 'before' },
  { word: 'кейін', english: 'after / later' },
  { word: 'әрқашан', english: 'always' },
  { word: 'кейде', english: 'sometimes' },
  { word: 'ешқашан', english: 'never' },
  { word: 'жиі', english: 'often' },
  { word: 'сирек', english: 'rarely' },
  { word: 'дүйсенбі', english: 'Monday' },
  { word: 'сейсенбі', english: 'Tuesday' },
  { word: 'сәрсенбі', english: 'Wednesday' },
  { word: 'бейсенбі', english: 'Thursday' },
  { word: 'жұма', english: 'Friday' },
  { word: 'сенбі', english: 'Saturday' },
  { word: 'жексенбі', english: 'Sunday' },
  { word: 'қаңтар', english: 'January' },
  { word: 'ақпан', english: 'February' },
  { word: 'наурыз', english: 'March' },
  { word: 'сәуір', english: 'April' },
  { word: 'мамыр', english: 'May' },
  { word: 'маусым', english: 'June' },
  { word: 'шілде', english: 'July' },
  { word: 'тамыз', english: 'August' },
  { word: 'қыркүйек', english: 'September' },
  { word: 'қазан', english: 'October' },
  { word: 'қараша', english: 'November' },
  { word: 'желтоқсан', english: 'December' },

  // Verbs
  { word: 'бару', english: 'to go' },
  { word: 'келу', english: 'to come' },
  { word: 'жүру', english: 'to walk / to go' },
  { word: 'жүгіру', english: 'to run' },
  { word: 'отыру', english: 'to sit' },
  { word: 'тұру', english: 'to stand / live' },
  { word: 'жату', english: 'to lie down' },
  { word: 'ұйықтау', english: 'to sleep' },
  { word: 'ояну', english: 'to wake up' },
  { word: 'істеу', english: 'to do' },
  { word: 'жасау', english: 'to make' },
  { word: 'айту', english: 'to say' },
  { word: 'сөйлеу', english: 'to speak' },
  { word: 'тыңдау', english: 'to listen' },
  { word: 'көру', english: 'to see' },
  { word: 'есту', english: 'to hear' },
  { word: 'оқу', english: 'to read / study' },
  { word: 'жазу', english: 'to write' },
  { word: 'үйрену', english: 'to learn' },
  { word: 'үйрету', english: 'to teach' },
  { word: 'білу', english: 'to know' },
  { word: 'түсіну', english: 'to understand' },
  { word: 'алу', english: 'to take' },
  { word: 'беру', english: 'to give' },
  { word: 'ашу', english: 'to open' },
  { word: 'жабу', english: 'to close' },
  { word: 'бастау', english: 'to start' },
  { word: 'аяқтау', english: 'to finish' },
  { word: 'күту', english: 'to wait' },
  { word: 'іздеу', english: 'to search' },
  { word: 'табу', english: 'to find' },
  { word: 'жоғалту', english: 'to lose' },
  { word: 'сұрау', english: 'to ask' },
  { word: 'жауап беру', english: 'to answer' },
  { word: 'көмектесу', english: 'to help' },
  { word: 'пайдалану', english: 'to use' },
  { word: 'қалау', english: 'to want' },
  { word: 'ұнату', english: 'to like' },
  { word: 'жақсы көру', english: 'to love' },
  { word: 'жек көру', english: 'to hate' },
  { word: 'ойлау', english: 'to think' },
  { word: 'сену', english: 'to believe' },
  { word: 'есте сақтау', english: 'to remember' },
  { word: 'ұмыту', english: 'to forget' },
  { word: 'келісу', english: 'to agree' },
  { word: 'келіспеу', english: 'to disagree' },
  { word: 'таңдау', english: 'to choose' },
  { word: 'сатып алу', english: 'to buy' },
  { word: 'сату', english: 'to sell' },
  { word: 'төлеу', english: 'to pay' },
  { word: 'жеу', english: 'to eat' },
  { word: 'ішу', english: 'to drink' },
  { word: 'пісіру', english: 'to cook' },
  { word: 'жуу', english: 'to wash' },
  { word: 'тазалау', english: 'to clean' },
  { word: 'жөндеу', english: 'to repair' },
  { word: 'ашулану', english: 'to get angry' },
  { word: 'күлу', english: 'to laugh' },
  { word: 'жылау', english: 'to cry' },
  { word: 'сүю', english: 'to kiss' },
  { word: 'ойнау', english: 'to play' },
  { word: 'жеңу', english: 'to win' },
  { word: 'ұтылу', english: 'to lose (a game)' },
  { word: 'болу', english: 'to be / to become' },
  { word: 'қалу', english: 'to stay' },
  { word: 'кету', english: 'to leave' },

  // Adjectives and descriptors
  { word: 'үлкен', english: 'big' },
  { word: 'кіші', english: 'small' },
  { word: 'ұзын', english: 'long' },
  { word: 'қысқа', english: 'short' },
  { word: 'кең', english: 'wide' },
  { word: 'тар', english: 'narrow' },
  { word: 'биік', english: 'high / tall' },
  { word: 'төмен', english: 'low' },
  { word: 'ауыр', english: 'heavy' },
  { word: 'жеңіл', english: 'light' },
  { word: 'жылы', english: 'warm' },
  { word: 'суық', english: 'cold' },
  { word: 'ыстық', english: 'hot' },
  { word: 'салқын', english: 'cool' },
  { word: 'жаңа', english: 'new' },
  { word: 'ескі', english: 'old (thing)' },
  { word: 'жас', english: 'young' },
  { word: 'кәрі', english: 'old (person)' },
  { word: 'жылдам', english: 'fast' },
  { word: 'баяу', english: 'slow' },
  { word: 'ерте', english: 'early' },
  { word: 'кеш', english: 'late' },
  { word: 'әдемі', english: 'beautiful' },
  { word: 'сұлу', english: 'pretty' },
  { word: 'күшті', english: 'strong' },
  { word: 'әлсіз', english: 'weak' },
  { word: 'батыл', english: 'brave' },
  { word: 'қорқақ', english: 'cowardly' },
  { word: 'бай', english: 'rich' },
  { word: 'кедей', english: 'poor' },
  { word: 'таза', english: 'clean' },
  { word: 'лас', english: 'dirty' },
  { word: 'қымбат', english: 'expensive' },
  { word: 'арзан', english: 'cheap' },
  { word: 'қиын', english: 'difficult' },
  { word: 'оңай', english: 'easy' },
  { word: 'маңызды', english: 'important' },
  { word: 'қызық', english: 'interesting' },
  { word: 'зеріктіргіш', english: 'boring' },
  { word: 'дұрыс', english: 'correct' },
  { word: 'қате', english: 'wrong' },
  { word: 'толық', english: 'full / complete' },
  { word: 'бос', english: 'empty / free' },
  { word: 'бақытты', english: 'happy' },
  { word: 'мұңды', english: 'sad' },
  { word: 'ашулы', english: 'angry' },
  { word: 'тыныш', english: 'calm / quiet' },
  { word: 'шаршаған', english: 'tired' },
  { word: 'қауіпті', english: 'dangerous' },
  { word: 'қауіпсіз', english: 'safe' },
  { word: 'жақын', english: 'near' },
  { word: 'алыс', english: 'far' },
  { word: 'белгілі', english: 'famous / known' },
  { word: 'бейтаныс', english: 'unfamiliar' },
  { word: 'ақылды', english: 'smart' },
  { word: 'әдепті', english: 'polite' },
  { word: 'адал', english: 'honest' },
  { word: 'мейірімді', english: 'kind' },
  { word: 'қатал', english: 'strict' },
  { word: 'ұқыпты', english: 'neat' },
  { word: 'лас емес', english: 'not dirty' },
  { word: 'тегін', english: 'free (no cost)' },
  { word: 'жеке', english: 'private / personal' },
  { word: 'ортақ', english: 'shared / common' },
];
