export default [
  { word: '안녕', english: 'hello (informal)' },
  { word: '안녕하세요', english: 'hello (formal)' },
  { word: '안녕하십니까', english: 'hello (very formal)' },
  { word: '좋은 아침이에요', english: 'good morning' },
  { word: '좋은 오후예요', english: 'good afternoon' },
  { word: '좋은 저녁이에요', english: 'good evening' },
  { word: '잘 자요', english: 'good night' },
  { word: '안녕히 가세요', english: 'goodbye (to person leaving)' },
  { word: '안녕히 계세요', english: 'goodbye (to person staying)' },
  { word: '또 봐요', english: 'see you' },
  { word: '내일 봐요', english: 'see you tomorrow' },
  { word: '오랜만이에요', english: 'long time no see' },
  { word: '만나서 반가워요', english: 'nice to meet you' },
  { word: '잘 지냈어요', english: 'have you been well' },
  { word: '저는 학생입니다', english: 'I am a student (formal)' },
  { word: '제 이름은 민수예요', english: 'my name is Minsu' },
  { word: '감사합니다', english: 'thank you' },
  { word: '고마워요', english: 'thanks' },
  { word: '정말 감사합니다', english: 'thank you very much' },
  { word: '천만에요', english: 'you are welcome' },
  { word: '실례합니다', english: 'excuse me' },
  { word: '죄송합니다', english: 'I am sorry' },
  { word: '미안해요', english: 'sorry' },
  { word: '괜찮아요', english: 'it is okay' },
  { word: '괜찮습니다', english: 'I am fine' },
  { word: '네', english: 'yes' },
  { word: '아니요', english: 'no' },
  { word: '맞아요', english: 'that is right' },
  { word: '아니에요', english: 'that is not right' },
  { word: '모르겠어요', english: 'I do not know' },
  { word: '알겠어요', english: 'I understand' },
  { word: '이해했어요', english: 'I understood' },
  { word: '이해 못했어요', english: 'I did not understand' },
  { word: '다시 말씀해 주세요', english: 'please say it again' },
  { word: '천천히 말씀해 주세요', english: 'please speak slowly' },
  { word: '도와주세요', english: 'please help me' },
  { word: '도움이 필요해요', english: 'I need help' },
  { word: '화이팅', english: 'you can do it' },
  { word: '축하해요', english: 'congratulations' },
  { word: '생일 축하해요', english: 'happy birthday' },
  { word: '새해 복 많이 받으세요', english: 'happy new year' },
  { word: '메리 크리스마스', english: 'merry christmas' },
  { word: '즐거운 하루 보내세요', english: 'have a nice day' },
  { word: '좋은 주말 보내세요', english: 'have a nice weekend' },
  { word: '잘 부탁드립니다', english: 'please take care of me' },
  { word: '부탁해요', english: 'please (request)' },
  { word: '잠시만요', english: 'just a moment' },
  { word: '기다려 주세요', english: 'please wait' },
  { word: '곧', english: 'soon' },
  { word: '벌써', english: 'already' },
  { word: '아직', english: 'not yet' },
  { word: '물론이에요', english: 'of course' },
  { word: '아마', english: 'maybe' },
  { word: '절대', english: 'never' },
  { word: '당연하죠', english: 'naturally' },
  { word: '정말이에요', english: 'it is true' },
  { word: '진짜요', english: 'really' },
  { word: '대박', english: 'awesome' },
  { word: '장난 아니에요', english: 'it is incredible' },
  { word: '최고예요', english: 'it is the best' },
  { word: '별로예요', english: 'not really' },
  { word: '상관없어요', english: 'it does not matter' },
  { word: '문제없어요', english: 'no problem' },
  { word: '힘내세요', english: 'cheer up' },
  { word: '수고하세요', english: 'take care at work' },
  { word: '수고했어요', english: 'good job' },
  { word: '잘했어요', english: 'well done' },
  { word: '반갑습니다', english: 'pleased to meet you' },
  { word: '잘 부탁해요', english: 'please treat me well' },
  { word: '여보세요', english: 'hello (on the phone)' },
  { word: '여기요', english: 'excuse me (to call staff)' },
  { word: '저기요', english: 'excuse me (to get attention)' },
  { word: '잠깐만요', english: 'wait a second' },
  { word: '실수했어요', english: 'I made a mistake' },
  { word: '확실해요', english: 'it is certain' },
  { word: '확인해 주세요', english: 'please check' },
  { word: '준비됐어요', english: 'I am ready' },
  { word: '끝났어요', english: 'it is finished' },
  { word: '시작합시다', english: 'let us start' },
  { word: '가족', english: 'family' },
  { word: '부모님', english: 'parents' },
  { word: '어머니', english: 'mother' },
  { word: '아버지', english: 'father' },
  { word: '엄마', english: 'mom' },
  { word: '아빠', english: 'dad' },
  { word: '할머니', english: 'grandmother' },
  { word: '할아버지', english: 'grandfather' },
  { word: '누나', english: 'older sister (for male)' },
  { word: '언니', english: 'older sister (for female)' },
  { word: '오빠', english: 'older brother (for female)' },
  { word: '형', english: 'older brother (for male)' },
  { word: '남동생', english: 'younger brother' },
  { word: '여동생', english: 'younger sister' },
  { word: '형제', english: 'siblings (brothers)' },
  { word: '자매', english: 'sisters' },
  { word: '남매', english: 'brother and sister' },
  { word: '아들', english: 'son' },
  { word: '딸', english: 'daughter' },
  { word: '아이', english: 'child' },
  { word: '아기', english: 'baby' },
  { word: '친척', english: 'relative' },
  { word: '사촌', english: 'cousin' },
  { word: '조카', english: 'nephew or niece' },
  { word: '손자', english: 'grandson' },
  { word: '손녀', english: 'granddaughter' },
  { word: '남편', english: 'husband' },
  { word: '아내', english: 'wife' },
  { word: '부부', english: 'married couple' },
  { word: '약혼자', english: 'fiance or fiancee' },
  { word: '친구', english: 'friend' },
  { word: '남자친구', english: 'boyfriend' },
  { word: '여자친구', english: 'girlfriend' },
  { word: '동료', english: 'coworker' },
  { word: '상사', english: 'boss' },
  { word: '부장', english: 'department manager' },
  { word: '사장', english: 'company president' },
  { word: '직원', english: 'employee' },
  { word: '손님', english: 'guest' },
  { word: '고객', english: 'customer' },
  { word: '이웃', english: 'neighbor' },
  { word: '선생님', english: 'teacher' },
  { word: '학생', english: 'student' },
  { word: '의사', english: 'doctor' },
  { word: '간호사', english: 'nurse' },
  { word: '경찰', english: 'police officer' },
  { word: '소방관', english: 'firefighter' },
  { word: '기사', english: 'driver' },
  { word: '요리사', english: 'cook' },
  { word: '가수', english: 'singer' },
  { word: '배우', english: 'actor' },
  { word: '작가', english: 'writer' },
  { word: '화가', english: 'painter' },
  { word: '운동선수', english: 'athlete' },
  { word: '사람', english: 'person' },
  { word: '성인', english: 'adult' },
  { word: '청소년', english: 'teenager' },
  { word: '어린이', english: 'young child' },
  { word: '노인', english: 'elderly person' },
  { word: '영', english: 'zero' },
  { word: '일', english: 'one (Sino Korean)' },
  { word: '이', english: 'two (Sino Korean)' },
  { word: '삼', english: 'three (Sino Korean)' },
  { word: '사', english: 'four (Sino Korean)' },
  { word: '오', english: 'five (Sino Korean)' },
  { word: '육', english: 'six (Sino Korean)' },
  { word: '칠', english: 'seven (Sino Korean)' },
  { word: '팔', english: 'eight (Sino Korean)' },
  { word: '구', english: 'nine (Sino Korean)' },
  { word: '십', english: 'ten (Sino Korean)' },
  { word: '백', english: 'hundred' },
  { word: '천', english: 'thousand' },
  { word: '만', english: 'ten thousand' },
  { word: '억', english: 'hundred million' },
  { word: '하나', english: 'one (native Korean)' },
  { word: '둘', english: 'two (native Korean)' },
  { word: '셋', english: 'three (native Korean)' },
  { word: '넷', english: 'four (native Korean)' },
  { word: '다섯', english: 'five (native Korean)' },
  { word: '여섯', english: 'six (native Korean)' },
  { word: '일곱', english: 'seven (native Korean)' },
  { word: '여덟', english: 'eight (native Korean)' },
  { word: '아홉', english: 'nine (native Korean)' },
  { word: '열', english: 'ten (native Korean)' },
  { word: '스물', english: 'twenty (native Korean)' },
  { word: '서른', english: 'thirty (native Korean)' },
  { word: '마흔', english: 'forty (native Korean)' },
  { word: '쉰', english: 'fifty (native Korean)' },
  { word: '예순', english: 'sixty (native Korean)' },
  { word: '일흔', english: 'seventy (native Korean)' },
  { word: '여든', english: 'eighty (native Korean)' },
  { word: '아흔', english: 'ninety (native Korean)' },
  { word: '첫째', english: 'first' },
  { word: '둘째', english: 'second' },
  { word: '셋째', english: 'third' },
  { word: '넷째', english: 'fourth' },
  { word: '다섯째', english: 'fifth' },
  { word: '개', english: 'counter for items' },
  { word: '명', english: 'counter for people' },
  { word: '분', english: 'minute; honorific person counter' },
  { word: '살', english: 'counter for age' },
  { word: '시', english: 'hour (clock)' },
  { word: '초', english: 'second (time)' },
  { word: '번', english: 'number of times' },
  { word: '층', english: 'floor (building)' },
  { word: '잔', english: 'cup or glass counter' },
  { word: '병', english: 'bottle counter' },
  { word: '권', english: 'book counter' },
  { word: '장', english: 'sheet counter' },
  { word: '마리', english: 'animal counter' },
  { word: '대', english: 'machine or vehicle counter' },
  { word: '채', english: 'house counter' },
  { word: '벌', english: 'set of clothes counter' },
  { word: '켤레', english: 'pair counter' },
  { word: '송이', english: 'flower cluster counter' },
  { word: '그릇', english: 'bowl counter' },
  { word: '시간', english: 'time' },
  { word: '날짜', english: 'date' },
  { word: '요일', english: 'day of week' },
  { word: '오늘', english: 'today' },
  { word: '어제', english: 'yesterday' },
  { word: '내일', english: 'tomorrow' },
  { word: '모레', english: 'day after tomorrow' },
  { word: '아침', english: 'morning' },
  { word: '점심', english: 'lunch' },
  { word: '저녁', english: 'evening' },
  { word: '밤', english: 'night' },
  { word: '새벽', english: 'dawn' },
  { word: '정오', english: 'noon' },
  { word: '자정', english: 'midnight' },
  { word: '주', english: 'week' },
  { word: '주말', english: 'weekend' },
  { word: '월요일', english: 'monday' },
  { word: '화요일', english: 'tuesday' },
  { word: '수요일', english: 'wednesday' },
  { word: '목요일', english: 'thursday' },
  { word: '금요일', english: 'friday' },
  { word: '토요일', english: 'saturday' },
  { word: '일요일', english: 'sunday' },
  { word: '월', english: 'month' },
  { word: '년', english: 'year' },
  { word: '봄', english: 'spring' },
  { word: '여름', english: 'summer' },
  { word: '가을', english: 'autumn' },
  { word: '겨울', english: 'winter' },
  { word: '밥', english: 'cooked rice; meal' },
  { word: '김치', english: 'kimchi' },
  { word: '불고기', english: 'bulgogi' },
  { word: '비빔밥', english: 'bibimbap' },
  { word: '잡채', english: 'japchae' },
  { word: '떡볶이', english: 'tteokbokki' },
  { word: '김밥', english: 'gimbap' },
  { word: '냉면', english: 'cold noodles' },
  { word: '갈비', english: 'rib meat' },
  { word: '삼겹살', english: 'pork belly' },
  { word: '된장찌개', english: 'soybean paste stew' },
  { word: '김치찌개', english: 'kimchi stew' },
  { word: '순두부찌개', english: 'soft tofu stew' },
  { word: '해장국', english: 'hangover soup' },
  { word: '설렁탕', english: 'ox bone soup' },
  { word: '삼계탕', english: 'ginseng chicken soup' },
  { word: '칼국수', english: 'knife cut noodle soup' },
  { word: '만두', english: 'dumpling' },
  { word: '라면', english: 'ramyeon instant noodles' },
  { word: '우동', english: 'udon noodles' },
  { word: '짜장면', english: 'black bean noodles' },
  { word: '짬뽕', english: 'spicy seafood noodles' },
  { word: '파전', english: 'green onion pancake' },
  { word: '빈대떡', english: 'mung bean pancake' },
  { word: '호떡', english: 'sweet filled pancake' },
  { word: '떡', english: 'rice cake' },
  { word: '순대', english: 'Korean blood sausage' },
  { word: '치킨', english: 'fried chicken' },
  { word: '피자', english: 'pizza' },
  { word: '햄버거', english: 'hamburger' },
  { word: '샌드위치', english: 'sandwich' },
  { word: '샐러드', english: 'salad' },
  { word: '계란', english: 'egg' },
  { word: '고기', english: 'meat' },
  { word: '생선', english: 'fish' },
  { word: '새우', english: 'shrimp' },
  { word: '오징어', english: 'squid' },
  { word: '조개', english: 'shellfish' },
  { word: '두부', english: 'tofu' },
  { word: '채소', english: 'vegetables' },
  { word: '과일', english: 'fruit' },
  { word: '사과', english: 'apple' },
  { word: '배', english: 'pear' },
  { word: '바나나', english: 'banana' },
  { word: '딸기', english: 'strawberry' },
  { word: '포도', english: 'grape' },
  { word: '수박', english: 'watermelon' },
  { word: '복숭아', english: 'peach' },
  { word: '토마토', english: 'tomato' },
  { word: '오이', english: 'cucumber' },
  { word: '당근', english: 'carrot' },
  { word: '감자', english: 'potato' },
  { word: '고구마', english: 'sweet potato' },
  { word: '양파', english: 'onion' },
  { word: '마늘', english: 'garlic' },
  { word: '버섯', english: 'mushroom' },
  { word: '빵', english: 'bread' },
  { word: '국', english: 'soup' },
  { word: '소금', english: 'salt' },
  { word: '설탕', english: 'sugar' },
  { word: '후추', english: 'pepper' },
  { word: '간장', english: 'soy sauce' },
  { word: '식초', english: 'vinegar' },
  { word: '기름', english: 'oil' },
  { word: '물', english: 'water' },
  { word: '커피', english: 'coffee' },
  { word: '차', english: 'tea' },
  { word: '우유', english: 'milk' },
  { word: '주스', english: 'juice' },
  { word: '맥주', english: 'beer' },
  { word: '소주', english: 'soju' },
  { word: '와인', english: 'wine' },
  { word: '막걸리', english: 'makgeolli' },
  { word: '음료수', english: 'soft drink' },
  { word: '디저트', english: 'dessert' },
  { word: '아이스크림', english: 'ice cream' },
  { word: '케이크', english: 'cake' },
  { word: '쿠키', english: 'cookie' },
  { word: '초콜릿', english: 'chocolate' },
  { word: '여행', english: 'travel' },
  { word: '관광', english: 'sightseeing' },
  { word: '관광객', english: 'tourist' },
  { word: '여권', english: 'passport' },
  { word: '비자', english: 'visa' },
  { word: '공항', english: 'airport' },
  { word: '비행기', english: 'airplane' },
  { word: '탑승권', english: 'boarding pass' },
  { word: '출국', english: 'departure from country' },
  { word: '입국', english: 'entry into country' },
  { word: '세관', english: 'customs' },
  { word: '짐', english: 'luggage' },
  { word: '수하물', english: 'checked baggage' },
  { word: '호텔', english: 'hotel' },
  { word: '예약', english: 'reservation' },
  { word: '체크인', english: 'check in' },
  { word: '체크아웃', english: 'check out' },
  { word: '열쇠', english: 'key' },
  { word: '객실', english: 'guest room' },
  { word: '프런트', english: 'front desk' },
  { word: '엘리베이터', english: 'elevator' },
  { word: '지도', english: 'map' },
  { word: '길', english: 'road; way' },
  { word: '주소', english: 'address' },
  { word: '목적지', english: 'destination' },
  { word: '출발', english: 'departure' },
  { word: '도착', english: 'arrival' },
  { word: '역', english: 'station' },
  { word: '기차', english: 'train' },
  { word: '지하철', english: 'subway' },
  { word: '버스', english: 'bus' },
  { word: '택시', english: 'taxi' },
  { word: '정류장', english: 'stop (bus stop)' },
  { word: '터미널', english: 'terminal' },
  { word: '항구', english: 'port' },
  { word: '배편', english: 'boat route' },
  { word: '고속도로', english: 'highway' },
  { word: '신호등', english: 'traffic light' },
  { word: '횡단보도', english: 'crosswalk' },
  { word: '사거리', english: 'intersection' },
  { word: '골목', english: 'alley' },
  { word: '왼쪽', english: 'left side' },
  { word: '오른쪽', english: 'right side' },
  { word: '직진', english: 'go straight' },
  { word: '북쪽', english: 'north' },
  { word: '남쪽', english: 'south' },
  { word: '동쪽', english: 'east' },
  { word: '서쪽', english: 'west' },
  { word: '근처', english: 'nearby' },
  { word: '멀리', english: 'far away' },
  { word: '앞', english: 'front' },
  { word: '뒤', english: 'back' },
  { word: '옆', english: 'side' },
  { word: '안', english: 'inside' },
  { word: '밖', english: 'outside' },
  { word: '위', english: 'above' },
  { word: '아래', english: 'below' },
  { word: '건너편', english: 'across from' },
  { word: '가운데', english: 'middle' },
  { word: '도시', english: 'city' },
  { word: '시골', english: 'countryside' },
  { word: '나라', english: 'country' },
  { word: '바다', english: 'sea' },
  { word: '산', english: 'mountain' },
  { word: '강', english: 'river' },
  { word: '호수', english: 'lake' },
  { word: '섬', english: 'island' },
  { word: '해변', english: 'beach' },
  { word: '공원', english: 'park' },
  { word: '박물관', english: 'museum' },
  { word: '미술관', english: 'art gallery' },
  { word: '궁궐', english: 'palace' },
  { word: '사찰', english: 'Buddhist temple' },
  { word: '성당', english: 'cathedral' },
  { word: '일자리', english: 'job' },
  { word: '직업', english: 'occupation' },
  { word: '회사', english: 'company' },
  { word: '사무실', english: 'office' },
  { word: '회의', english: 'meeting' },
  { word: '보고서', english: 'report' },
  { word: '이메일', english: 'email' },
  { word: '전화', english: 'phone call' },
  { word: '일정', english: 'schedule' },
  { word: '마감', english: 'deadline' },
  { word: '프로젝트', english: 'project' },
  { word: '팀', english: 'team' },
  { word: '부서', english: 'department' },
  { word: '업무', english: 'work task' },
  { word: '출근', english: 'go to work' },
  { word: '퇴근', english: 'leave work' },
  { word: '휴가', english: 'vacation' },
  { word: '월급', english: 'salary' },
  { word: '보너스', english: 'bonus' },
  { word: '계약', english: 'contract' },
  { word: '면접', english: 'interview' },
  { word: '이력서', english: 'resume' },
  { word: '채용', english: 'hiring' },
  { word: '실업', english: 'unemployment' },
  { word: '학교', english: 'school' },
  { word: '교실', english: 'classroom' },
  { word: '수업', english: 'class lesson' },
  { word: '강의', english: 'lecture' },
  { word: '시험', english: 'exam' },
  { word: '숙제', english: 'homework' },
  { word: '문제', english: 'problem' },
  { word: '답', english: 'answer' },
  { word: '질문', english: 'question' },
  { word: '연습', english: 'practice' },
  { word: '공부', english: 'study' },
  { word: '학습', english: 'learning' },
  { word: '복습', english: 'review' },
  { word: '졸업', english: 'graduation' },
  { word: '등록', english: 'registration' },
  { word: '도서관', english: 'library' },
  { word: '책상', english: 'desk' },
  { word: '의자', english: 'chair' },
  { word: '노트', english: 'notebook' },
  { word: '펜', english: 'pen' },
  { word: '연필', english: 'pencil' },
  { word: '지우개', english: 'eraser' },
  { word: '공책', english: 'exercise notebook' },
  { word: '칠판', english: 'blackboard' },
  { word: '과목', english: 'subject' },
  { word: '수학', english: 'mathematics' },
  { word: '과학', english: 'science' },
  { word: '역사', english: 'history' },
  { word: '언어', english: 'language' },
  { word: '경제', english: 'economics' },
  { word: '법률', english: 'law' },
  { word: '몸', english: 'body' },
  { word: '머리', english: 'head' },
  { word: '얼굴', english: 'face' },
  { word: '눈', english: 'eye' },
  { word: '코', english: 'nose' },
  { word: '입', english: 'mouth' },
  { word: '귀', english: 'ear' },
  { word: '치아', english: 'tooth' },
  { word: '목', english: 'neck' },
  { word: '어깨', english: 'shoulder' },
  { word: '팔뚝', english: 'arm' },
  { word: '손', english: 'hand' },
  { word: '손가락', english: 'finger' },
  { word: '가슴', english: 'chest' },
  { word: '등', english: 'back' },
  { word: '허리', english: 'waist' },
  { word: '복부', english: 'abdomen' },
  { word: '엉덩이', english: 'hip' },
  { word: '다리', english: 'leg' },
  { word: '무릎', english: 'knee' },
  { word: '발', english: 'foot' },
  { word: '발가락', english: 'toe' },
  { word: '피부', english: 'skin' },
  { word: '피', english: 'blood' },
  { word: '뼈', english: 'bone' },
  { word: '심장', english: 'heart' },
  { word: '폐', english: 'lung' },
  { word: '간', english: 'liver' },
  { word: '위장', english: 'stomach' },
  { word: '장기', english: 'organ' },
  { word: '근육', english: 'muscle' },
  { word: '감기', english: 'cold illness' },
  { word: '열감', english: 'feverish feeling' },
  { word: '기침', english: 'cough' },
  { word: '콧물', english: 'runny nose' },
  { word: '두통', english: 'headache' },
  { word: '복통', english: 'stomachache' },
  { word: '병원', english: 'hospital' },
  { word: '약국', english: 'pharmacy' },
  { word: '약', english: 'medicine' },
  { word: '주사', english: 'injection' },
  { word: '수술', english: 'surgery' },
  { word: '진료', english: 'medical treatment' },
  { word: '건강', english: 'health' },
  { word: '운동', english: 'exercise' },
  { word: '스트레칭', english: 'stretching' },
  { word: '휴식', english: 'rest' },
  { word: '잠', english: 'sleep' },
  { word: '통증', english: 'pain' },
  { word: '상처', english: 'wound' },
  { word: '붕대', english: 'bandage' },
  { word: '체온', english: 'body temperature' },
  { word: '혈압', english: 'blood pressure' },
  { word: '알레르기', english: 'allergy' },
  { word: '예방접종', english: 'vaccination' },
  { word: '하다', english: 'to do' },
  { word: '가다', english: 'to go' },
  { word: '오다', english: 'to come' },
  { word: '보다', english: 'to see' },
  { word: '듣다', english: 'to listen' },
  { word: '말하다', english: 'to speak' },
  { word: '읽다', english: 'to read' },
  { word: '쓰다', english: 'to write' },
  { word: '먹다', english: 'to eat' },
  { word: '마시다', english: 'to drink' },
  { word: '자다', english: 'to sleep' },
  { word: '일어나다', english: 'to get up' },
  { word: '씻다', english: 'to wash' },
  { word: '입다', english: 'to wear' },
  { word: '벗다', english: 'to take off clothes' },
  { word: '걷다', english: 'to walk' },
  { word: '달리다', english: 'to run' },
  { word: '앉다', english: 'to sit' },
  { word: '서다', english: 'to stand' },
  { word: '쉬다', english: 'to rest' },
  { word: '공부하다', english: 'to study' },
  { word: '일하다', english: 'to work' },
  { word: '놀다', english: 'to play' },
  { word: '사다', english: 'to buy' },
  { word: '팔다', english: 'to sell' },
  { word: '만들다', english: 'to make' },
  { word: '사용하다', english: 'to use' },
  { word: '고치다', english: 'to fix' },
  { word: '배우다', english: 'to learn' },
  { word: '가르치다', english: 'to teach' },
  { word: '시작하다', english: 'to start' },
  { word: '끝나다', english: 'to end' },
  { word: '기다리다', english: 'to wait' },
  { word: '찾다', english: 'to find' },
  { word: '잃어버리다', english: 'to lose' },
  { word: '만나다', english: 'to meet' },
  { word: '헤어지다', english: 'to part from' },
  { word: '사랑하다', english: 'to love' },
  { word: '좋아하다', english: 'to like' },
  { word: '싫어하다', english: 'to dislike' },
  { word: '기억하다', english: 'to remember' },
  { word: '잊다', english: 'to forget' },
  { word: '선택하다', english: 'to choose' },
  { word: '결정하다', english: 'to decide' },
  { word: '설명하다', english: 'to explain' },
  { word: '질문하다', english: 'to ask' },
  { word: '대답하다', english: 'to answer' },
  { word: '전화하다', english: 'to call by phone' },
  { word: '문자하다', english: 'to text' },
  { word: '보내다', english: 'to send' },
  { word: '받다', english: 'to receive' },
  { word: '열다', english: 'to open' },
  { word: '닫다', english: 'to close' },
  { word: '켜다', english: 'to turn on' },
  { word: '끄다', english: 'to turn off' },
  { word: '타다', english: 'to ride' },
  { word: '내리다', english: 'to get off' },
  { word: '빌리다', english: 'to borrow' },
  { word: '돌려주다', english: 'to return something' },
  { word: '주문하다', english: 'to order' },
  { word: '요리하다', english: 'to cook' },
  { word: '청소하다', english: 'to clean' },
  { word: '정리하다', english: 'to organize' },
  { word: '세탁하다', english: 'to do laundry' },
  { word: '운전하다', english: 'to drive' },
  { word: '주차하다', english: 'to park' },
  { word: '여행하다', english: 'to travel' },
  { word: '예약하다', english: 'to reserve' },
  { word: '취소하다', english: 'to cancel' },
  { word: '결제하다', english: 'to pay' },
  { word: '연습하다', english: 'to practice' },
  { word: '준비하다', english: 'to prepare' },
  { word: '확인하다', english: 'to confirm' },
  { word: '비교하다', english: 'to compare' },
  { word: '추천하다', english: 'to recommend' },
  { word: '동의하다', english: 'to agree' },
  { word: '반대하다', english: 'to oppose' },
  { word: '도착하다', english: 'to arrive' },
  { word: '출발하다', english: 'to depart' },
  { word: '좋다', english: 'to be good' },
  { word: '나쁘다', english: 'to be bad' },
  { word: '크다', english: 'to be big' },
  { word: '작다', english: 'to be small' },
  { word: '길다', english: 'to be long' },
  { word: '짧다', english: 'to be short' },
  { word: '빠르다', english: 'to be fast' },
  { word: '느리다', english: 'to be slow' },
  { word: '쉽다', english: 'to be easy' },
  { word: '어렵다', english: 'to be difficult' },
  { word: '뜨겁다', english: 'to be hot' },
  { word: '차갑다', english: 'to be cold' },
  { word: '따뜻하다', english: 'to be warm' },
  { word: '시원하다', english: 'to be cool' },
  { word: '맵다', english: 'to be spicy' },
  { word: '달다', english: 'to be sweet' },
  { word: '짜다', english: 'to be salty' },
  { word: '쓰디쓰다', english: 'to be very bitter' },
  { word: '시다', english: 'to be sour' },
  { word: '비싸다', english: 'to be expensive' },
  { word: '싸다', english: 'to be cheap' },
  { word: '깨끗하다', english: 'to be clean' },
  { word: '더럽다', english: 'to be dirty' },
  { word: '조용하다', english: 'to be quiet' },
  { word: '시끄럽다', english: 'to be noisy' },
  { word: '바쁘다', english: 'to be busy' },
  { word: '한가하다', english: 'to be free' },
  { word: '행복하다', english: 'to be happy' },
  { word: '슬프다', english: 'to be sad' },
  { word: '화나다', english: 'to be angry' },
  { word: '무섭다', english: 'to be scary' },
  { word: '재미있다', english: 'to be fun' },
  { word: '지루하다', english: 'to be boring' },
  { word: '친절하다', english: 'to be kind' },
  { word: '불친절하다', english: 'to be unkind' },
  { word: '중요하다', english: 'to be important' },
  { word: '필요하다', english: 'to be necessary' },
  { word: '가능하다', english: 'to be possible' },
  { word: '불가능하다', english: 'to be impossible' },
  { word: '안전하다', english: 'to be safe' },
  { word: '위험하다', english: 'to be dangerous' },
  { word: '유명하다', english: 'to be famous' },
  { word: '특별하다', english: 'to be special' },
  { word: '평범하다', english: 'to be ordinary' },
  { word: '정확하다', english: 'to be accurate' },
  { word: '틀리다', english: 'to be wrong' },
  { word: '젊다', english: 'to be young' },
  { word: '늙다', english: 'to be old' },
  { word: '아프다', english: 'to be sick' },
  { word: '배고프다', english: 'to be hungry' },
  { word: '목마르다', english: 'to be thirsty' },
  { word: '졸리다', english: 'to be sleepy' },
  { word: '피곤하다', english: 'to be tired' },
  { word: '예쁘다', english: 'to be pretty' },
  { word: '아름답다', english: 'to be beautiful' },
  { word: '잘생기다', english: 'to be handsome' },
  { word: '귀엽다', english: 'to be cute' },
  { word: '멋있다', english: 'to be cool' },
  { word: '똑똑하다', english: 'to be smart' },
  { word: '게으르다', english: 'to be lazy' },
  { word: '부지런하다', english: 'to be diligent' },
  { word: '편하다', english: 'to be comfortable' },
  { word: '불편하다', english: 'to be uncomfortable' },
  { word: '케이팝', english: 'K pop' },
  { word: '아이돌', english: 'idol performer' },
  { word: '연습생', english: 'trainee idol' },
  { word: '컴백', english: 'comeback release' },
  { word: '팬덤', english: 'fandom' },
  { word: '응원봉', english: 'light stick' },
  { word: '팬사인회', english: 'fan signing event' },
  { word: '콘서트', english: 'concert' },
  { word: '무대', english: 'stage' },
  { word: '안무', english: 'choreography' },
  { word: '노래', english: 'song' },
  { word: '랩', english: 'rap' },
  { word: '댄스', english: 'dance' },
  { word: '뮤직비디오', english: 'music video' },
  { word: '드라마', english: 'drama series' },
  { word: '예능', english: 'variety show' },
  { word: '웹툰', english: 'webtoon' },
  { word: '한류', english: 'Korean wave' },
  { word: '한복', english: 'hanbok' },
  { word: '한글', english: 'Korean alphabet' },
  { word: '태권도', english: 'taekwondo' },
  { word: '노래방', english: 'karaoke room' },
  { word: '찜질방', english: 'Korean sauna' },
  { word: '편의점', english: 'convenience store' },
  { word: '배달', english: 'delivery' },
  { word: '집', english: 'house' },
  { word: '방', english: 'room' },
  { word: '거실', english: 'living room' },
  { word: '부엌', english: 'kitchen' },
  { word: '욕실', english: 'bathroom' },
  { word: '화장실', english: 'toilet' },
  { word: '침대', english: 'bed' },
  { word: '이불', english: 'blanket' },
  { word: '베개', english: 'pillow' },
  { word: '문', english: 'door' },
  { word: '창문', english: 'window' },
  { word: '냉장고', english: 'refrigerator' },
  { word: '세탁기', english: 'washing machine' },
  { word: '청소기', english: 'vacuum cleaner' },
  { word: '에어컨', english: 'air conditioner' },
  { word: '난방', english: 'heating' },
  { word: '전등', english: 'light lamp' },
  { word: '리모컨', english: 'remote control' },
  { word: '인터넷', english: 'internet' },
  { word: '와이파이', english: 'Wi Fi' },
  { word: '비밀번호', english: 'password' },
  { word: '계정', english: 'account' },
  { word: '로그인', english: 'log in' },
  { word: '로그아웃', english: 'log out' },
  { word: '앱', english: 'app' },
  { word: '프로그램', english: 'program' },
  { word: '소프트웨어', english: 'software' },
  { word: '하드웨어', english: 'hardware' },
  { word: '파일', english: 'file' },
  { word: '폴더', english: 'folder' },
  { word: '다운로드', english: 'download' },
  { word: '업로드', english: 'upload' },
  { word: '링크', english: 'link' },
  { word: '화면', english: 'screen' },
  { word: '키보드', english: 'keyboard' },
  { word: '마우스', english: 'mouse' },
  { word: '모니터', english: 'monitor' },
  { word: '태블릿', english: 'tablet' },
  { word: '스마트폰', english: 'smartphone' },
  { word: '충전기', english: 'charger' },
  { word: '배터리', english: 'battery' },
  { word: '이어폰', english: 'earphones' },
  { word: '헤드폰', english: 'headphones' },
  { word: '카메라', english: 'camera' },
  { word: '사진', english: 'photo' },
  { word: '동영상', english: 'video clip' },
  { word: '메시지', english: 'message' },
  { word: '알림', english: 'notification' },
  { word: '검색', english: 'search' },
  { word: '쇼핑', english: 'shopping' },
  { word: '가게', english: 'shop' },
  { word: '상점', english: 'store' },
  { word: '시장', english: 'market' },
  { word: '마트', english: 'mart' },
  { word: '백화점', english: 'department store' },
  { word: '가격', english: 'price' },
  { word: '할인', english: 'discount' },
  { word: '쿠폰', english: 'coupon' },
  { word: '영수증', english: 'receipt' },
  { word: '계산대', english: 'checkout counter' },
  { word: '카드', english: 'card' },
  { word: '현금', english: 'cash' },
  { word: '지갑', english: 'wallet' },
  { word: '동전', english: 'coin' },
  { word: '지폐', english: 'banknote' },
  { word: '환불', english: 'refund' },
  { word: '교환', english: 'exchange' },
  { word: '사이즈', english: 'size' },
  { word: '색깔', english: 'color' },
  { word: '재고', english: 'stock inventory' },
  { word: '품절', english: 'sold out' },
  { word: '날씨', english: 'weather' },
  { word: '비', english: 'rain' },
  { word: '눈보라', english: 'snowstorm' },
  { word: '바람', english: 'wind' },
  { word: '구름', english: 'cloud' },
  { word: '하늘', english: 'sky' },
  { word: '태양', english: 'sun' },
  { word: '맑음', english: 'clear weather' },
  { word: '흐림', english: 'cloudy weather' },
  { word: '폭염', english: 'heat wave' },
  { word: '한파', english: 'cold wave' },
  { word: '습도', english: 'humidity' },
  { word: '기온', english: 'air temperature' },
  { word: '우산', english: 'umbrella' },
  { word: '장화', english: 'rain boots' },
  { word: '무지개', english: 'rainbow' },
  { word: '태풍', english: 'typhoon' },
  { word: '번개', english: 'lightning' },
  { word: '천둥', english: 'thunder' },
  { word: '안개', english: 'fog' },
  { word: '서리', english: 'frost' },
];
