export default [
  // Greetings and common expressions
  { word: 'привет', english: 'hello (informal)' },
  { word: 'здравствуйте', english: 'hello (formal)' },
  { word: 'доброе утро', english: 'good morning' },
  { word: 'добрый день', english: 'good afternoon' },
  { word: 'добрый вечер', english: 'good evening' },
  { word: 'спокойной ночи', english: 'good night' },
  { word: 'пока', english: 'bye (informal)' },
  { word: 'до свидания', english: 'goodbye (formal)' },
  { word: 'увидимся', english: 'see you' },
  { word: 'до встречи', english: 'see you later' },
  { word: 'спасибо', english: 'thank you' },
  { word: 'большое спасибо', english: 'thank you very much' },
  { word: 'пожалуйста', english: 'please / you are welcome' },
  { word: 'извините', english: 'excuse me' },
  { word: 'простите', english: 'sorry' },
  { word: 'да', english: 'yes' },
  { word: 'нет', english: 'no' },
  { word: 'может быть', english: 'maybe' },
  { word: 'конечно', english: 'of course' },
  { word: 'хорошо', english: 'okay / good' },
  { word: 'я понимаю', english: 'I understand' },
  { word: 'я не понимаю', english: 'I do not understand' },
  { word: 'повторите, пожалуйста', english: 'please repeat' },
  { word: 'говорите медленнее', english: 'speak more slowly' },
  { word: 'вы говорите по-русски', english: 'do you speak Russian' },
  { word: 'вы говорите по-английски', english: 'do you speak English' },
  { word: 'меня зовут', english: 'my name is' },
  { word: 'как дела', english: 'how are you' },
  { word: 'все хорошо', english: 'everything is fine' },
  { word: 'приятно познакомиться', english: 'nice to meet you' },
  { word: 'откуда вы', english: 'where are you from' },
  { word: 'я забыл', english: 'I forgot' },
  { word: 'я не знаю', english: 'I do not know' },
  { word: 'помогите, пожалуйста', english: 'please help' },
  { word: 'мне нужна помощь', english: 'I need help' },
  { word: 'без проблем', english: 'no problem' },
  { word: 'удачи', english: 'good luck' },
  { word: 'поздравляю', english: 'congratulations' },
  { word: 'приятного аппетита', english: 'enjoy your meal' },
  { word: 'берегите себя', english: 'take care' },
  { word: 'до завтра', english: 'see you tomorrow' },
  { word: 'счастливого пути', english: 'have a good trip' },
  { word: 'я согласен', english: 'I agree' },
  { word: 'я не согласен', english: 'I disagree' },
  { word: 'мне нравится', english: 'I like it' },
  { word: 'мне не нравится', english: 'I do not like it' },
  { word: 'очень хорошо', english: 'very good' },
  { word: 'очень плохо', english: 'very bad' },
  { word: 'не важно', english: 'it does not matter' },
  { word: 'подождите минуту', english: 'wait a minute' },
  { word: 'не спешите', english: 'do not hurry' },
  { word: 'я слушаю', english: 'I am listening' },
  { word: 'ответьте, пожалуйста', english: 'please answer' },
  { word: 'сейчас', english: 'right now' },
  { word: 'позже', english: 'later' },
  { word: 'уже', english: 'already' },
  { word: 'еще нет', english: 'not yet' },
  { word: 'это верно', english: 'that is correct' },
  { word: 'это неверно', english: 'that is incorrect' },
  { word: 'возможно', english: 'possible / perhaps' },

  // Family and people
  { word: 'семья', english: 'family' },
  { word: 'родители', english: 'parents' },
  { word: 'мать', english: 'mother' },
  { word: 'отец', english: 'father' },
  { word: 'мама', english: 'mom' },
  { word: 'папа', english: 'dad' },
  { word: 'дедушка', english: 'grandfather' },
  { word: 'бабушка', english: 'grandmother' },
  { word: 'брат', english: 'brother' },
  { word: 'сестра', english: 'sister' },
  { word: 'старший брат', english: 'older brother' },
  { word: 'младший брат', english: 'younger brother' },
  { word: 'старшая сестра', english: 'older sister' },
  { word: 'младшая сестра', english: 'younger sister' },
  { word: 'сын', english: 'son' },
  { word: 'дочь', english: 'daughter' },
  { word: 'ребенок', english: 'child' },
  { word: 'малыш', english: 'baby' },
  { word: 'внук', english: 'grandson' },
  { word: 'внучка', english: 'granddaughter' },
  { word: 'муж', english: 'husband' },
  { word: 'жена', english: 'wife' },
  { word: 'супруг', english: 'spouse (male)' },
  { word: 'супруга', english: 'spouse (female)' },
  { word: 'родственник', english: 'relative' },
  { word: 'дядя', english: 'uncle' },
  { word: 'тетя', english: 'aunt' },
  { word: 'двоюродный брат', english: 'cousin (male)' },
  { word: 'двоюродная сестра', english: 'cousin (female)' },
  { word: 'друг', english: 'friend (male)' },
  { word: 'подруга', english: 'friend (female)' },
  { word: 'сосед', english: 'neighbor (male)' },
  { word: 'соседка', english: 'neighbor (female)' },
  { word: 'гость', english: 'guest (male)' },
  { word: 'гостья', english: 'guest (female)' },
  { word: 'учитель', english: 'teacher (male)' },
  { word: 'учительница', english: 'teacher (female)' },
  { word: 'врач', english: 'doctor' },
  { word: 'инженер', english: 'engineer' },
  { word: 'повар', english: 'cook' },
  { word: 'водитель', english: 'driver' },
  { word: 'продавец', english: 'seller' },
  { word: 'клиент', english: 'client' },
  { word: 'коллега', english: 'colleague' },
  { word: 'начальник', english: 'boss' },
  { word: 'сотрудник', english: 'employee' },
  { word: 'команда', english: 'team' },

  // Numbers
  { word: 'ноль', english: 'zero' },
  { word: 'один', english: 'one' },
  { word: 'два', english: 'two' },
  { word: 'три', english: 'three' },
  { word: 'четыре', english: 'four' },
  { word: 'пять', english: 'five' },
  { word: 'шесть', english: 'six' },
  { word: 'семь', english: 'seven' },
  { word: 'восемь', english: 'eight' },
  { word: 'девять', english: 'nine' },
  { word: 'десять', english: 'ten' },
  { word: 'одиннадцать', english: 'eleven' },
  { word: 'двенадцать', english: 'twelve' },
  { word: 'тринадцать', english: 'thirteen' },
  { word: 'четырнадцать', english: 'fourteen' },
  { word: 'пятнадцать', english: 'fifteen' },
  { word: 'шестнадцать', english: 'sixteen' },
  { word: 'семнадцать', english: 'seventeen' },
  { word: 'восемнадцать', english: 'eighteen' },
  { word: 'девятнадцать', english: 'nineteen' },
  { word: 'двадцать', english: 'twenty' },
  { word: 'двадцать один', english: 'twenty one' },
  { word: 'двадцать два', english: 'twenty two' },
  { word: 'двадцать три', english: 'twenty three' },
  { word: 'двадцать четыре', english: 'twenty four' },
  { word: 'двадцать пять', english: 'twenty five' },
  { word: 'двадцать шесть', english: 'twenty six' },
  { word: 'двадцать семь', english: 'twenty seven' },
  { word: 'двадцать восемь', english: 'twenty eight' },
  { word: 'двадцать девять', english: 'twenty nine' },
  { word: 'тридцать', english: 'thirty' },
  { word: 'тридцать один', english: 'thirty one' },
  { word: 'тридцать два', english: 'thirty two' },
  { word: 'тридцать три', english: 'thirty three' },
  { word: 'тридцать четыре', english: 'thirty four' },
  { word: 'тридцать пять', english: 'thirty five' },
  { word: 'тридцать шесть', english: 'thirty six' },
  { word: 'тридцать семь', english: 'thirty seven' },
  { word: 'тридцать восемь', english: 'thirty eight' },
  { word: 'тридцать девять', english: 'thirty nine' },
  { word: 'сорок', english: 'forty' },
  { word: 'сорок один', english: 'forty one' },
  { word: 'сорок два', english: 'forty two' },
  { word: 'сорок три', english: 'forty three' },
  { word: 'сорок четыре', english: 'forty four' },
  { word: 'сорок пять', english: 'forty five' },
  { word: 'сорок шесть', english: 'forty six' },
  { word: 'сорок семь', english: 'forty seven' },
  { word: 'сорок восемь', english: 'forty eight' },
  { word: 'сорок девять', english: 'forty nine' },
  { word: 'пятьдесят', english: 'fifty' },
  { word: 'шестьдесят', english: 'sixty' },
  { word: 'семьдесят', english: 'seventy' },
  { word: 'восемьдесят', english: 'eighty' },
  { word: 'девяносто', english: 'ninety' },
  { word: 'сто', english: 'one hundred' },
  { word: 'тысяча', english: 'thousand' },
  { word: 'миллион', english: 'million' },
  { word: 'первый', english: 'first' },
  { word: 'второй', english: 'second' },
  { word: 'третий', english: 'third' },
  { word: 'четвертый', english: 'fourth' },
  { word: 'пятый', english: 'fifth' },

  // Food and drink
  { word: 'еда', english: 'food' },
  { word: 'блюдо', english: 'dish' },
  { word: 'хлеб', english: 'bread' },
  { word: 'вода', english: 'water' },
  { word: 'чай', english: 'tea' },
  { word: 'кофе', english: 'coffee' },
  { word: 'молоко', english: 'milk' },
  { word: 'кефир', english: 'kefir' },
  { word: 'сок', english: 'juice' },
  { word: 'сахар', english: 'sugar' },
  { word: 'соль', english: 'salt' },
  { word: 'перец', english: 'pepper' },
  { word: 'мясо', english: 'meat' },
  { word: 'говядина', english: 'beef' },
  { word: 'баранина', english: 'lamb' },
  { word: 'курица', english: 'chicken' },
  { word: 'рыба', english: 'fish' },
  { word: 'яйцо', english: 'egg' },
  { word: 'рис', english: 'rice' },
  { word: 'макароны', english: 'pasta' },
  { word: 'каша', english: 'porridge' },
  { word: 'суп', english: 'soup' },
  { word: 'салат', english: 'salad' },
  { word: 'картофель', english: 'potato' },
  { word: 'морковь', english: 'carrot' },
  { word: 'лук', english: 'onion' },
  { word: 'чеснок', english: 'garlic' },
  { word: 'помидор', english: 'tomato' },
  { word: 'огурец', english: 'cucumber' },
  { word: 'капуста', english: 'cabbage' },
  { word: 'болгарский перец', english: 'bell pepper' },
  { word: 'яблоко', english: 'apple' },
  { word: 'груша', english: 'pear' },
  { word: 'банан', english: 'banana' },
  { word: 'апельсин', english: 'orange' },
  { word: 'лимон', english: 'lemon' },
  { word: 'виноград', english: 'grape' },
  { word: 'арбуз', english: 'watermelon' },
  { word: 'дыня', english: 'melon' },
  { word: 'клубника', english: 'strawberry' },
  { word: 'вишня', english: 'cherry' },
  { word: 'абрикос', english: 'apricot' },
  { word: 'персик', english: 'peach' },
  { word: 'орех', english: 'nut' },
  { word: 'сыр', english: 'cheese' },
  { word: 'масло', english: 'butter / oil' },
  { word: 'мед', english: 'honey' },
  { word: 'десерт', english: 'dessert' },
  { word: 'мороженое', english: 'ice cream' },
  { word: 'пирог', english: 'pie' },
  { word: 'плов', english: 'pilaf' },
  { word: 'вкусный', english: 'tasty' },
  { word: 'острый', english: 'spicy' },
  { word: 'я сыт', english: 'I am full' },
  { word: 'я голоден', english: 'I am hungry' },
  { word: 'я хочу пить', english: 'I am thirsty' },
  { word: 'принесите счет', english: 'bring the bill' },

  // Travel and city
  { word: 'поездка', english: 'trip' },
  { word: 'путешествие', english: 'travel' },
  { word: 'дорога', english: 'road' },
  { word: 'улица', english: 'street' },
  { word: 'проспект', english: 'avenue' },
  { word: 'поворот', english: 'turn' },
  { word: 'направление', english: 'direction' },
  { word: 'адрес', english: 'address' },
  { word: 'город', english: 'city' },
  { word: 'деревня', english: 'village' },
  { word: 'страна', english: 'country' },
  { word: 'центр', english: 'center' },
  { word: 'аэропорт', english: 'airport' },
  { word: 'вокзал', english: 'station' },
  { word: 'остановка', english: 'stop' },
  { word: 'билет', english: 'ticket' },
  { word: 'самолет', english: 'airplane' },
  { word: 'поезд', english: 'train' },
  { word: 'автобус', english: 'bus' },
  { word: 'такси', english: 'taxi' },
  { word: 'метро', english: 'metro' },
  { word: 'транспорт', english: 'transport' },
  { word: 'машина', english: 'car' },
  { word: 'водительские права', english: 'driver license' },
  { word: 'отель', english: 'hotel' },
  { word: 'номер', english: 'hotel room' },
  { word: 'ключ', english: 'key' },
  { word: 'бронь', english: 'reservation' },
  { word: 'паспорт', english: 'passport' },
  { word: 'граница', english: 'border' },
  { word: 'таможня', english: 'customs' },
  { word: 'карта', english: 'map' },
  { word: 'касса', english: 'ticket office' },
  { word: 'стоимость проезда', english: 'fare' },
  { word: 'поверните налево', english: 'turn left' },
  { word: 'поверните направо', english: 'turn right' },
  { word: 'идите прямо', english: 'go straight' },
  { word: 'это недалеко', english: 'it is not far' },
  { word: 'рядом', english: 'nearby' },
  { word: 'где находится', english: 'where is located' },
  { word: 'где аптека', english: 'where is the pharmacy' },
  { word: 'где туалет', english: 'where is the toilet' },
  { word: 'я заблудился', english: 'I am lost' },
  { word: 'мне нужно такси', english: 'I need a taxi' },
  { word: 'отвезите меня сюда', english: 'take me here' },
  { word: 'билет в одну сторону', english: 'one-way ticket' },
  { word: 'билет туда и обратно', english: 'round-trip ticket' },

  // Work and study
  { word: 'работа', english: 'work' },
  { word: 'офис', english: 'office' },
  { word: 'компания', english: 'company' },
  { word: 'организация', english: 'organization' },
  { word: 'проект', english: 'project' },
  { word: 'задача', english: 'task' },
  { word: 'обязанность', english: 'duty' },
  { word: 'цель', english: 'goal' },
  { word: 'план', english: 'plan' },
  { word: 'расписание', english: 'schedule' },
  { word: 'встреча', english: 'meeting' },
  { word: 'отчет', english: 'report' },
  { word: 'результат', english: 'result' },
  { word: 'опыт', english: 'experience' },
  { word: 'навык', english: 'skill' },
  { word: 'знание', english: 'knowledge' },
  { word: 'урок', english: 'lesson' },
  { word: 'экзамен', english: 'exam' },
  { word: 'домашнее задание', english: 'homework' },
  { word: 'зарплата', english: 'salary' },
  { word: 'премия', english: 'bonus' },
  { word: 'договор', english: 'contract' },
  { word: 'подпись', english: 'signature' },
  { word: 'документ', english: 'document' },
  { word: 'письмо', english: 'letter' },
  { word: 'электронная почта', english: 'email' },
  { word: 'звонок', english: 'call' },
  { word: 'собеседование', english: 'interview' },
  { word: 'отпуск', english: 'vacation' },
  { word: 'перерыв', english: 'break' },
  { word: 'рабочий день', english: 'workday' },
  { word: 'рабочее время', english: 'working hours' },
  { word: 'полный день', english: 'full time' },
  { word: 'неполный день', english: 'part time' },
  { word: 'должность', english: 'position' },
  { word: 'карьера', english: 'career' },
  { word: 'совет', english: 'advice' },
  { word: 'решение', english: 'decision' },
  { word: 'мнение', english: 'opinion' },
  { word: 'вопрос', english: 'question' },
  { word: 'ответ', english: 'answer' },

  // Body and health
  { word: 'тело', english: 'body' },
  { word: 'голова', english: 'head' },
  { word: 'лицо', english: 'face' },
  { word: 'глаз', english: 'eye' },
  { word: 'ухо', english: 'ear' },
  { word: 'нос', english: 'nose' },
  { word: 'рот', english: 'mouth' },
  { word: 'губа', english: 'lip' },
  { word: 'зуб', english: 'tooth' },
  { word: 'язык', english: 'tongue' },
  { word: 'челюсть', english: 'jaw' },
  { word: 'шея', english: 'neck' },
  { word: 'плечо', english: 'shoulder' },
  { word: 'рука', english: 'arm / hand' },
  { word: 'локоть', english: 'elbow' },
  { word: 'запястье', english: 'wrist' },
  { word: 'ладонь', english: 'palm' },
  { word: 'палец', english: 'finger' },
  { word: 'ноготь', english: 'nail' },
  { word: 'грудь', english: 'chest' },
  { word: 'спина', english: 'back' },
  { word: 'талия', english: 'waist' },
  { word: 'живот', english: 'belly' },
  { word: 'сердце', english: 'heart' },
  { word: 'легкое', english: 'lung' },
  { word: 'желудок', english: 'stomach' },
  { word: 'печень', english: 'liver' },
  { word: 'нога', english: 'leg / foot' },
  { word: 'бедро', english: 'thigh' },
  { word: 'колено', english: 'knee' },
  { word: 'икра', english: 'calf' },
  { word: 'пятка', english: 'heel' },
  { word: 'стопа', english: 'foot' },
  { word: 'кровь', english: 'blood' },
  { word: 'кожа', english: 'skin' },
  { word: 'кость', english: 'bone' },
  { word: 'мышца', english: 'muscle' },
  { word: 'боль', english: 'pain' },
  { word: 'здоровье', english: 'health' },
  { word: 'лекарство', english: 'medicine' },
  { word: 'больница', english: 'hospital' },
  { word: 'поликлиника', english: 'clinic' },
  { word: 'скорая помощь', english: 'ambulance' },
  { word: 'температура', english: 'temperature' },
  { word: 'у меня болит голова', english: 'I have a headache' },
  { word: 'я плохо себя чувствую', english: 'I feel unwell' },

  // Time and calendar
  { word: 'время', english: 'time' },
  { word: 'час', english: 'hour' },
  { word: 'минута', english: 'minute' },
  { word: 'секунда', english: 'second' },
  { word: 'день', english: 'day' },
  { word: 'неделя', english: 'week' },
  { word: 'месяц', english: 'month' },
  { word: 'год', english: 'year' },
  { word: 'сегодня', english: 'today' },
  { word: 'вчера', english: 'yesterday' },
  { word: 'завтра', english: 'tomorrow' },
  { word: 'утром', english: 'in the morning' },
  { word: 'днем', english: 'in the daytime' },
  { word: 'вечером', english: 'in the evening' },
  { word: 'ночью', english: 'at night' },
  { word: 'сначала', english: 'first / at first' },
  { word: 'потом', english: 'then / later' },
  { word: 'до', english: 'before / until' },
  { word: 'после', english: 'after' },
  { word: 'всегда', english: 'always' },
  { word: 'иногда', english: 'sometimes' },
  { word: 'никогда', english: 'never' },
  { word: 'часто', english: 'often' },
  { word: 'редко', english: 'rarely' },
  { word: 'понедельник', english: 'Monday' },
  { word: 'вторник', english: 'Tuesday' },
  { word: 'среда', english: 'Wednesday' },
  { word: 'четверг', english: 'Thursday' },
  { word: 'пятница', english: 'Friday' },
  { word: 'суббота', english: 'Saturday' },
  { word: 'воскресенье', english: 'Sunday' },
  { word: 'январь', english: 'January' },
  { word: 'февраль', english: 'February' },
  { word: 'март', english: 'March' },
  { word: 'апрель', english: 'April' },
  { word: 'май', english: 'May' },
  { word: 'июнь', english: 'June' },
  { word: 'июль', english: 'July' },
  { word: 'август', english: 'August' },
  { word: 'сентябрь', english: 'September' },
  { word: 'октябрь', english: 'October' },
  { word: 'ноябрь', english: 'November' },
  { word: 'декабрь', english: 'December' },

  // Verbs
  { word: 'быть', english: 'to be' },
  { word: 'идти', english: 'to go (on foot)' },
  { word: 'ходить', english: 'to walk / go regularly' },
  { word: 'ехать', english: 'to go by transport' },
  { word: 'приходить', english: 'to come' },
  { word: 'уходить', english: 'to leave' },
  { word: 'бежать', english: 'to run' },
  { word: 'сидеть', english: 'to sit' },
  { word: 'стоять', english: 'to stand' },
  { word: 'лежать', english: 'to lie down' },
  { word: 'спать', english: 'to sleep' },
  { word: 'просыпаться', english: 'to wake up' },
  { word: 'делать', english: 'to do' },
  { word: 'сделать', english: 'to make / to do (perfective)' },
  { word: 'говорить', english: 'to speak' },
  { word: 'сказать', english: 'to say' },
  { word: 'слушать', english: 'to listen' },
  { word: 'слышать', english: 'to hear' },
  { word: 'смотреть', english: 'to watch / look' },
  { word: 'видеть', english: 'to see' },
  { word: 'читать', english: 'to read' },
  { word: 'писать', english: 'to write' },
  { word: 'учиться', english: 'to study / learn' },
  { word: 'учить', english: 'to teach / learn' },
  { word: 'знать', english: 'to know' },
  { word: 'понимать', english: 'to understand' },
  { word: 'брать', english: 'to take' },
  { word: 'давать', english: 'to give' },
  { word: 'открывать', english: 'to open' },
  { word: 'закрывать', english: 'to close' },
  { word: 'начинать', english: 'to start' },
  { word: 'заканчивать', english: 'to finish' },
  { word: 'ждать', english: 'to wait' },
  { word: 'искать', english: 'to search' },
  { word: 'находить', english: 'to find' },
  { word: 'терять', english: 'to lose' },
  { word: 'спрашивать', english: 'to ask' },
  { word: 'отвечать', english: 'to answer' },
  { word: 'помогать', english: 'to help' },
  { word: 'использовать', english: 'to use' },
  { word: 'хотеть', english: 'to want' },
  { word: 'любить', english: 'to love' },
  { word: 'нравиться', english: 'to be liked' },
  { word: 'ненавидеть', english: 'to hate' },
  { word: 'думать', english: 'to think' },
  { word: 'верить', english: 'to believe' },
  { word: 'помнить', english: 'to remember' },
  { word: 'забывать', english: 'to forget' },
  { word: 'соглашаться', english: 'to agree' },
  { word: 'отказываться', english: 'to refuse' },
  { word: 'выбирать', english: 'to choose' },
  { word: 'покупать', english: 'to buy' },
  { word: 'продавать', english: 'to sell' },
  { word: 'платить', english: 'to pay' },
  { word: 'есть', english: 'to eat' },
  { word: 'пить', english: 'to drink' },
  { word: 'готовить', english: 'to cook' },
  { word: 'мыть', english: 'to wash' },
  { word: 'чистить', english: 'to clean' },
  { word: 'ремонтировать', english: 'to repair' },
  { word: 'злиться', english: 'to get angry' },
  { word: 'смеяться', english: 'to laugh' },
  { word: 'плакать', english: 'to cry' },
  { word: 'играть', english: 'to play' },
  { word: 'побеждать', english: 'to win' },
  { word: 'проигрывать', english: 'to lose (a game)' },

  // Adjectives and descriptors
  { word: 'большой', english: 'big' },
  { word: 'маленький', english: 'small' },
  { word: 'длинный', english: 'long' },
  { word: 'короткий', english: 'short' },
  { word: 'широкий', english: 'wide' },
  { word: 'узкий', english: 'narrow' },
  { word: 'высокий', english: 'high / tall' },
  { word: 'низкий', english: 'low' },
  { word: 'тяжелый', english: 'heavy' },
  { word: 'легкий', english: 'light / easy' },
  { word: 'теплый', english: 'warm' },
  { word: 'холодный', english: 'cold' },
  { word: 'горячий', english: 'hot' },
  { word: 'прохладный', english: 'cool' },
  { word: 'новый', english: 'new' },
  { word: 'старый', english: 'old' },
  { word: 'молодой', english: 'young' },
  { word: 'быстрый', english: 'fast' },
  { word: 'медленный', english: 'slow' },
  { word: 'ранний', english: 'early' },
  { word: 'поздний', english: 'late' },
  { word: 'красивый', english: 'beautiful' },
  { word: 'сильный', english: 'strong' },
  { word: 'слабый', english: 'weak' },
  { word: 'смелый', english: 'brave' },
  { word: 'богатый', english: 'rich' },
  { word: 'бедный', english: 'poor' },
  { word: 'чистый', english: 'clean' },
  { word: 'грязный', english: 'dirty' },
  { word: 'дорогой', english: 'expensive' },
  { word: 'дешевый', english: 'cheap' },
  { word: 'сложный', english: 'difficult' },
  { word: 'простой', english: 'simple' },
  { word: 'важный', english: 'important' },
  { word: 'интересный', english: 'interesting' },
  { word: 'скучный', english: 'boring' },
  { word: 'правильный', english: 'correct' },
  { word: 'неправильный', english: 'wrong' },
  { word: 'полный', english: 'full' },
  { word: 'пустой', english: 'empty' },
  { word: 'счастливый', english: 'happy' },
  { word: 'грустный', english: 'sad' },
  { word: 'злой', english: 'angry' },
  { word: 'спокойный', english: 'calm' },
  { word: 'уставший', english: 'tired' },
  { word: 'опасный', english: 'dangerous' },
  { word: 'безопасный', english: 'safe' },
  { word: 'близкий', english: 'near' },
  { word: 'далекий', english: 'far' },
  { word: 'известный', english: 'famous' },
  { word: 'незнакомый', english: 'unfamiliar' },
  { word: 'умный', english: 'smart' },
  { word: 'вежливый', english: 'polite' },
  { word: 'честный', english: 'honest' },
  { word: 'добрый', english: 'kind' },
  { word: 'строгий', english: 'strict' },
  { word: 'аккуратный', english: 'neat' },
  { word: 'бесплатный', english: 'free (no cost)' },
  { word: 'личный', english: 'personal' },
  { word: 'общий', english: 'shared / common' },
];
