/**
 * Curated topic word pools + learner theory for Match Madness.
 * Imported by scripts/build-topics.mjs
 */

function w(french, english, extra = {}) {
  return { french, english, ...extra };
}

export const TOPIC_DEFINITIONS = [
  {
    id: 'numbers',
    label: 'Numbers',
    frenchLabel: 'Les nombres',
    emoji: '🔢',
    accent: 'blue',
    description: 'Count, compare, and use numbers in prices, ages, and phone digits.',
    theory: [
      { type: 'rule', title: 'Un vs une', text: 'Use <strong>un</strong> (m) and <strong>une</strong> (f) for “one/a” — the number agrees with the noun: <em>un livre</em>, <em>une pomme</em>.' },
      { type: 'tip', text: 'French groups big numbers in threes: <em>quatre-vingt-dix-neuf</em> (4×20+19) = 99. Belgium/Switzerland often say <em>nonante-neuf</em> instead.' },
      { type: 'example', fr: 'J\'ai vingt-cinq ans.', en: 'I am twenty-five years old.', note: 'Age uses avoir, not être' },
      { type: 'callout', variant: 'compare-en', text: '🇬🇧 English says “twenty-one”; French hyphenates compound numbers under 100: <em>vingt-et-un</em> (with et before one).' },
    ],
    words: [
      w('zéro', 'zero'), w('un', 'one', { context: 'a/an (m)' }), w('une', 'one', { context: 'a/an (f)' }),
      w('deux', 'two'), w('trois', 'three'), w('quatre', 'four'), w('cinq', 'five'),
      w('six', 'six'), w('sept', 'seven'), w('huit', 'eight'), w('neuf', 'nine'), w('dix', 'ten'),
      w('onze', 'eleven'), w('douze', 'twelve'), w('treize', 'thirteen'), w('quatorze', 'fourteen'),
      w('quinze', 'fifteen'), w('seize', 'sixteen'), w('vingt', 'twenty'), w('trente', 'thirty'),
      w('quarante', 'forty'), w('cinquante', 'fifty'), w('soixante', 'sixty'),
      w('cent', 'hundred'), w('mille', 'thousand'), w('premier', 'first', { context: 'm' }),
      w('première', 'first', { context: 'f' }), w('deuxième', 'second'), w('demi', 'half'),
    ],
  },
  {
    id: 'dates-times',
    label: 'Dates & Times',
    frenchLabel: 'Dates et heures',
    emoji: '📅',
    accent: 'teal',
    description: 'Ask the time, set appointments, and read calendar dates naturally.',
    theory: [
      { type: 'rule', title: 'Telling time', text: 'Use <strong>Il est</strong> + hour: <em>Il est trois heures</em>. Add <em>et quart</em> (quarter past), <em>et demie</em> (half past), <em>moins le quart</em> (quarter to).' },
      { type: 'rule', title: '24-hour clock', text: 'Schedules and transport use 24h: <em>14h30</em> = 2:30 PM. In speech: <em>quatorze heures trente</em>.' },
      { type: 'example', fr: 'Le rendez-vous est le 3 mars à 15 heures.', en: 'The appointment is March 3rd at 3 PM.' },
      { type: 'tip', text: 'Dates: <em>le 5 mai</em> (the 5th of May). First of month: <em>le premier janvier</em>.' },
    ],
    words: [
      w('heure', 'hour', { article: 'l\'', context: 'time / o\'clock' }), w('minute', 'minute', { article: 'la' }),
      w('seconde', 'second', { article: 'la' }), w('matin', 'morning', { article: 'le' }),
      w('après-midi', 'afternoon', { article: 'l\'' }), w('soir', 'evening', { article: 'le' }),
      w('nuit', 'night', { article: 'la' }), w('midi', 'noon'), w('minuit', 'midnight'),
      w('aujourd\'hui', 'today'), w('hier', 'yesterday'), w('demain', 'tomorrow'),
      w('semaine', 'week', { article: 'la' }), w('week-end', 'weekend', { article: 'le' }),
      w('date', 'date', { article: 'la' }), w('calendrier', 'calendar', { article: 'le' }),
      w('rendez-vous', 'appointment', { article: 'le' }), w('retard', 'delay', { article: 'le' }),
      w('à l\'heure', 'on time'), w('en avance', 'early'), w('en retard', 'late'),
      w('Quelle heure est-il ?', 'What time is it?'), w('Il est une heure.', 'It is one o\'clock.'),
    ],
  },
  {
    id: 'days',
    label: 'Days of the Week',
    frenchLabel: 'Les jours',
    emoji: '📆',
    accent: 'green',
    description: 'Schedule your week — all days are masculine and usually lowercase.',
    theory: [
      { type: 'rule', title: 'Gender & articles', text: 'Days are masculine: <em>le lundi</em>. Use <em>le</em> for recurring events: <em>Je travaille le lundi</em> = I work on Mondays.' },
      { type: 'tip', text: 'Weekend spans <em>samedi</em> and <em>dimanche</em>. Monday–Friday = <em>en semaine</em> (during the week).' },
      { type: 'example', fr: 'On se voit samedi prochain.', en: 'We\'ll see each other next Saturday.' },
    ],
    words: [
      w('lundi', 'Monday'), w('mardi', 'Tuesday'), w('mercredi', 'Wednesday'),
      w('jeudi', 'Thursday'), w('vendredi', 'Friday'), w('samedi', 'Saturday'), w('dimanche', 'Sunday'),
      w('jour', 'day', { article: 'le' }), w('journée', 'daytime / whole day', { article: 'la' }),
      w('chaque jour', 'every day'), w('tous les jours', 'every day'), w('le week-end', 'the weekend'),
      w('en semaine', 'on weekdays'), w('la semaine prochaine', 'next week'), w('la semaine dernière', 'last week'),
    ],
  },
  {
    id: 'months-seasons',
    label: 'Months & Seasons',
    frenchLabel: 'Mois et saisons',
    emoji: '🗓️',
    accent: 'orange',
    description: 'Months, seasons, and weather-linked vocabulary for planning ahead.',
    theory: [
      { type: 'rule', title: 'Months', text: 'Months are masculine and not capitalized: <em>en janvier</em>, <em>au mois de mars</em>.' },
      { type: 'rule', title: 'Seasons', text: 'Seasons are feminine: <em>en été</em>, <em>au printemps</em> (spring uses <em>au</em> because printemps is masc.).' },
      { type: 'example', fr: 'Nous partons en vacances en juillet.', en: 'We\'re going on holiday in July.' },
    ],
    words: [
      w('janvier', 'January'), w('février', 'February'), w('mars', 'March'), w('avril', 'April'),
      w('mai', 'May'), w('juin', 'June'), w('juillet', 'July'), w('août', 'August'),
      w('septembre', 'September'), w('octobre', 'October'), w('novembre', 'November'), w('décembre', 'December'),
      w('printemps', 'spring', { article: 'le' }), w('été', 'summer', { article: 'l\'' }),
      w('automne', 'autumn', { article: 'l\'' }), w('hiver', 'winter', { article: 'l\'' }),
      w('mois', 'month', { article: 'le' }), w('année', 'year', { article: 'l\'' }),
      w('saison', 'season', { article: 'la' }), w('vacances', 'holidays / vacation', { article: 'les' }),
    ],
  },
  {
    id: 'colors',
    label: 'Colors',
    frenchLabel: 'Les couleurs',
    emoji: '🎨',
    accent: 'pink',
    description: 'Describe objects — most colors agree in gender and number with the noun.',
    theory: [
      { type: 'rule', title: 'Agreement', text: 'Add <strong>-e</strong> for feminine, <strong>-s</strong> for plural: <em>une voiture rouge</em>, <em>des fleurs rouges</em>.' },
      { type: 'tip', text: 'Invariable colors (no agreement): <em>orange, marron, crème, bleu marine, bleu ciel</em>.' },
      { type: 'example', fr: 'Elle porte une robe bleue et des chaussures noires.', en: 'She\'s wearing a blue dress and black shoes.' },
    ],
    words: [
      w('rouge', 'red'), w('bleu', 'blue'), w('vert', 'green'), w('jaune', 'yellow'),
      w('noir', 'black'), w('blanc', 'white'), w('gris', 'gray'), w('rose', 'pink'),
      w('orange', 'orange'), w('marron', 'brown'), w('violet', 'purple'), w('beige', 'beige'),
      w('doré', 'golden'), w('argenté', 'silver'), w('clair', 'light'), w('foncé', 'dark'),
      w('couleur', 'color', { article: 'la' }), w('multicolore', 'multicolored'),
    ],
  },
  {
    id: 'food-drink',
    label: 'Food & Drink',
    frenchLabel: 'Nourriture',
    emoji: '🍽️',
    accent: 'amber',
    description: 'Order at cafés, talk about meals, and use partitive articles with food.',
    theory: [
      { type: 'rule', title: 'Partitive articles', text: '<em>du pain</em> (some bread), <em>de la viande</em>, <em>de l\'eau</em>, <em>des légumes</em>. After negation: <em>pas de pain</em>.' },
      { type: 'tip', text: 'Meals: <em>petit-déjeuner</em> (breakfast), <em>déjeuner</em> (lunch), <em>dîner</em> (dinner). In France lunch is often the main meal.' },
      { type: 'example', fr: 'Je voudrais un café et un croissant, s\'il vous plaît.', en: 'I\'d like a coffee and a croissant, please.' },
    ],
    words: [
      w('pain', 'bread', { article: 'le' }), w('fromage', 'cheese', { article: 'le' }),
      w('beurre', 'butter', { article: 'le' }), w('œuf', 'egg', { article: 'l\'' }),
      w('viande', 'meat', { article: 'la' }), w('poisson', 'fish', { article: 'le' }),
      w('poulet', 'chicken', { article: 'le' }), w('riz', 'rice', { article: 'le' }),
      w('pâtes', 'pasta', { article: 'les' }), w('soupe', 'soup', { article: 'la' }),
      w('salade', 'salad', { article: 'la' }), w('dessert', 'dessert', { article: 'le' }),
      w('eau', 'water', { article: 'l\'' }), w('café', 'coffee', { article: 'le' }),
      w('thé', 'tea', { article: 'le' }), w('lait', 'milk', { article: 'le' }),
      w('vin', 'wine', { article: 'le' }), w('bière', 'beer', { article: 'la' }),
      w('sucre', 'sugar', { article: 'le' }), w('sel', 'salt', { article: 'le' }),
      w('restaurant', 'restaurant', { article: 'le' }), w('menu', 'menu', { article: 'le' }),
      w('addition', 'bill / check', { article: 'l\'' }), w('J\'ai faim.', 'I\'m hungry.'), w('J\'ai soif.', 'I\'m thirsty.'),
    ],
  },
  {
    id: 'fruits-vegetables',
    label: 'Fruits & Vegetables',
    frenchLabel: 'Fruits et légumes',
    emoji: '🥬',
    accent: 'green',
    description: 'Market vocabulary — many fruits are feminine, many vegetables masculine (with exceptions!).',
    theory: [
      { type: 'tip', text: 'At the market: <em>Je voudrais un kilo de tomates, s\'il vous plaît.</em> Weights: <em>un kilo</em>, <em>500 grammes</em>.' },
      { type: 'callout', variant: 'warning', text: 'Memorize gender with the article: <em>la pomme</em> but <em>le citron</em> — endings don\'t always predict gender.' },
    ],
    words: [
      w('pomme', 'apple', { article: 'la' }), w('banane', 'banana', { article: 'la' }),
      w('orange', 'orange', { article: 'l\'' }), w('fraise', 'strawberry', { article: 'la' }),
      w('raisin', 'grape', { article: 'le' }), w('cerise', 'cherry', { article: 'la' }),
      w('citron', 'lemon', { article: 'le' }), w('poire', 'pear', { article: 'la' }),
      w('tomate', 'tomato', { article: 'la' }), w('carotte', 'carrot', { article: 'la' }),
      w('pomme de terre', 'potato', { article: 'la' }), w('oignon', 'onion', { article: 'l\'' }),
      w('ail', 'garlic', { article: 'l\'' }), w('salade', 'lettuce / salad', { article: 'la' }),
      w('concombre', 'cucumber', { article: 'le' }), w('poivron', 'bell pepper', { article: 'le' }),
      w('champignon', 'mushroom', { article: 'le' }), w('haricot', 'bean', { article: 'le' }),
      w('légume', 'vegetable', { article: 'le' }), w('fruit', 'fruit', { article: 'le' }),
      w('marché', 'market', { article: 'le' }),
    ],
  },
  {
    id: 'family',
    label: 'Family',
    frenchLabel: 'La famille',
    emoji: '👨‍👩‍👧',
    accent: 'rose',
    description: 'Relatives, relationships, and possessive structures with family.',
    theory: [
      { type: 'rule', title: 'Possessives', text: '<em>mon père</em>, <em>ma mère</em>, <em>mes parents</em>. Before vowel: <em>mon amie</em> (f) because <em>ma amie</em> would clash.' },
      { type: 'example', fr: 'Ma sœur a deux enfants.', en: 'My sister has two children.' },
    ],
    words: [
      w('famille', 'family', { article: 'la' }), w('parent', 'parent', { article: 'le' }),
      w('parents', 'parents', { article: 'les' }), w('père', 'father', { article: 'le' }),
      w('mère', 'mother', { article: 'la' }), w('fils', 'son', { article: 'le' }),
      w('fille', 'daughter / girl', { article: 'la' }), w('frère', 'brother', { article: 'le' }),
      w('sœur', 'sister', { article: 'la' }), w('grand-père', 'grandfather', { article: 'le' }),
      w('grand-mère', 'grandmother', { article: 'la' }), w('oncle', 'uncle', { article: 'l\'' }),
      w('tante', 'aunt', { article: 'la' }), w('cousin', 'cousin (m)', { article: 'le' }),
      w('cousine', 'cousin (f)', { article: 'la' }), w('mari', 'husband', { article: 'le' }),
      w('femme', 'wife / woman', { article: 'la' }), w('enfant', 'child', { article: 'l\'' }),
      w('bébé', 'baby', { article: 'le' }), w('marié', 'married'), w('célibataire', 'single'),
    ],
  },
  {
    id: 'body',
    label: 'Body Parts',
    frenchLabel: 'Le corps',
    emoji: '🫀',
    accent: 'red',
    description: 'Head to toe — French often uses definite articles where English uses possessives.',
    theory: [
      { type: 'rule', title: 'Definite article for body', text: '<em>J\'ai mal à la tête</em> (literally: I have pain to the head) = I have a headache. Same pattern: <em>mal aux dents</em>.' },
      { type: 'example', fr: 'Il s\'est cassé le bras.', en: 'He broke his arm.' },
    ],
    words: [
      w('tête', 'head', { article: 'la' }), w('yeux', 'eyes', { article: 'les' }),
      w('œil', 'eye', { article: 'l\'' }), w('nez', 'nose', { article: 'le' }),
      w('bouche', 'mouth', { article: 'la' }), w('oreille', 'ear', { article: 'l\'' }),
      w('dent', 'tooth', { article: 'la' }), w('cou', 'neck', { article: 'le' }),
      w('épaule', 'shoulder', { article: 'l\'' }), w('bras', 'arm', { article: 'le' }),
      w('main', 'hand', { article: 'la' }), w('doigt', 'finger', { article: 'le' }),
      w('jambe', 'leg', { article: 'la' }), w('pied', 'foot', { article: 'le' }),
      w('dos', 'back', { article: 'le' }), w('ventre', 'belly', { article: 'le' }),
      w('cœur', 'heart', { article: 'le' }), w('mal', 'pain / ache', { article: 'le' }),
      w('J\'ai mal à la tête.', 'I have a headache.'),
    ],
  },
  {
    id: 'clothing',
    label: 'Clothing',
    frenchLabel: 'Les vêtements',
    emoji: '👕',
    accent: 'purple',
    description: 'What you wear — verbs <em>porter</em> (wear) and <em>mettre</em> (put on).',
    theory: [
      { type: 'rule', title: 'Verbs', text: '<em>porter</em> = to wear (state). <em>mettre</em> = to put on. <em>enlever</em> = to take off.' },
      { type: 'example', fr: 'Il fait froid — mets ton manteau !', en: 'It\'s cold — put on your coat!' },
    ],
    words: [
      w('vêtement', 'clothing', { article: 'le' }), w('chemise', 'shirt', { article: 'la' }),
      w('pantalon', 'trousers', { article: 'le' }), w('jean', 'jeans', { article: 'le' }),
      w('robe', 'dress', { article: 'la' }), w('jupe', 'skirt', { article: 'la' }),
      w('manteau', 'coat', { article: 'le' }), w('veste', 'jacket', { article: 'la' }),
      w('pull', 'sweater', { article: 'le' }), w('chaussure', 'shoe', { article: 'la' }),
      w('chaussette', 'sock', { article: 'la' }), w('chapeau', 'hat', { article: 'le' }),
      w('casquette', 'cap', { article: 'la' }), w('cravate', 'tie', { article: 'la' }),
      w('ceinture', 'belt', { article: 'la' }), w('sac', 'bag', { article: 'le' }),
      w('taille', 'size', { article: 'la' }), w('porter', 'to wear'), w('mettre', 'to put on'),
    ],
  },
  {
    id: 'home',
    label: 'Home & Furniture',
    frenchLabel: 'La maison',
    emoji: '🏠',
    accent: 'teal',
    description: 'Rooms, furniture, and everyday household items.',
    theory: [
      { type: 'tip', text: '<em>Chez moi</em> = at my place. <em>À la maison</em> = at home. <em>Il y a</em> = there is/are for describing rooms.' },
      { type: 'example', fr: 'La cuisine est à côté du salon.', en: 'The kitchen is next to the living room.' },
    ],
    words: [
      w('maison', 'house', { article: 'la' }), w('appartement', 'apartment', { article: 'l\'' }),
      w('chambre', 'bedroom', { article: 'la' }), w('salon', 'living room', { article: 'le' }),
      w('cuisine', 'kitchen', { article: 'la' }), w('salle de bain', 'bathroom', { article: 'la' }),
      w('toilettes', 'toilet', { article: 'les' }), w('porte', 'door', { article: 'la' }),
      w('fenêtre', 'window', { article: 'la' }), w('lit', 'bed', { article: 'le' }),
      w('table', 'table', { article: 'la' }), w('chaise', 'chair', { article: 'la' }),
      w('canapé', 'sofa', { article: 'le' }), w('armoire', 'wardrobe', { article: 'l\'' }),
      w('lampe', 'lamp', { article: 'la' }), w('miroir', 'mirror', { article: 'le' }),
      w('clé', 'key', { article: 'la' }), w('ascenseur', 'elevator', { article: 'l\'' }),
      w('étage', 'floor / storey', { article: 'l\'' }), w('jardin', 'garden', { article: 'le' }),
    ],
  },
  {
    id: 'school',
    label: 'School & Education',
    frenchLabel: 'L\'école',
    emoji: '🎓',
    accent: 'blue',
    description: 'Classroom, subjects, and study vocabulary.',
    theory: [
      { type: 'rule', title: 'School system', text: '<em>l\'école primaire</em> (primary), <em>le collège</em> (~11–15), <em>le lycée</em> (high school), <em>l\'université</em>.' },
      { type: 'example', fr: 'J\'étudie le français à l\'université.', en: 'I study French at university.' },
    ],
    words: [
      w('école', 'school', { article: 'l\'' }), w('classe', 'class', { article: 'la' }),
      w('professeur', 'teacher', { article: 'le' }), w('élève', 'student (school)', { article: 'l\'' }),
      w('étudiant', 'student (university)', { article: 'l\'' }), w('cours', 'class / course', { article: 'le' }),
      w('devoir', 'homework', { article: 'le' }), w('examen', 'exam', { article: 'l\'' }),
      w('crayon', 'pencil', { article: 'le' }), w('stylo', 'pen', { article: 'le' }),
      w('cahier', 'notebook', { article: 'le' }), w('livre', 'book', { article: 'le' }),
      w('bibliothèque', 'library', { article: 'la' }), w('mathématiques', 'math', { article: 'les' }),
      w('histoire', 'history', { article: 'l\'' }), w('géographie', 'geography', { article: 'la' }),
      w('langue', 'language', { article: 'la' }), w('apprendre', 'to learn'), w('étudier', 'to study'),
    ],
  },
  {
    id: 'work',
    label: 'Work & Professions',
    frenchLabel: 'Le travail',
    emoji: '💼',
    accent: 'amber',
    description: 'Jobs, the office, and talking about what you do for a living.',
    theory: [
      { type: 'rule', title: 'Professions without article', text: 'After <em>être</em>: <em>Il est médecin</em>, <em>Elle est avocate</em> — no article for profession (informal standard).' },
      { type: 'example', fr: 'Je travaille dans une banque à Lyon.', en: 'I work at a bank in Lyon.' },
    ],
    words: [
      w('travail', 'work', { article: 'le' }), w('bureau', 'office / desk', { article: 'le' }),
      w('entreprise', 'company', { article: 'l\'' }), w('patron', 'boss', { article: 'le' }),
      w('collègue', 'colleague', { article: 'le' }), w('salaire', 'salary', { article: 'le' }),
      w('réunion', 'meeting', { article: 'la' }), w('contrat', 'contract', { article: 'le' }),
      w('médecin', 'doctor'), w('infirmier', 'nurse (m)'), w('avocat', 'lawyer (m)'),
      w('ingénieur', 'engineer'), w('serveur', 'waiter'), w('serveuse', 'waitress'),
      w('cuisinier', 'cook (m)'), w('vendeur', 'salesperson (m)'), w('employé', 'employee (m)'),
      w('chômage', 'unemployment', { article: 'le' }), w('travailler', 'to work'), w('gagner', 'to earn'),
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    frenchLabel: 'Les animaux',
    emoji: '🐾',
    accent: 'green',
    description: 'Pets, farm animals, and wildlife — learn gender with each noun.',
    theory: [
      { type: 'tip', text: 'Pet phrases: <em>J\'ai un chat</em> / <em>Je promène le chien</em>. Animal sounds differ: French dogs say <em>ouaf ouaf</em>!' },
    ],
    words: [
      w('animal', 'animal', { article: 'l\'' }), w('chien', 'dog', { article: 'le' }),
      w('chat', 'cat', { article: 'le' }), w('oiseau', 'bird', { article: 'l\'' }),
      w('poisson', 'fish', { article: 'le' }), w('cheval', 'horse', { article: 'le' }),
      w('vache', 'cow', { article: 'la' }), w('cochon', 'pig', { article: 'le' }),
      w('mouton', 'sheep', { article: 'le' }), w('poule', 'hen', { article: 'la' }),
      w('lapin', 'rabbit', { article: 'le' }), w('souris', 'mouse', { article: 'la' }),
      w('lion', 'lion', { article: 'le' }), w('éléphant', 'elephant', { article: 'l\'' }),
      w('ours', 'bear', { article: 'l\'' }), w('serpent', 'snake', { article: 'le' }),
      w('insecte', 'insect', { article: 'l\'' }), w('zoo', 'zoo', { article: 'le' }),
    ],
  },
  {
    id: 'nature-weather',
    label: 'Nature & Weather',
    frenchLabel: 'La nature',
    emoji: '🌤️',
    accent: 'teal',
    description: 'Sky, seasons, and describing the weather with <em>il fait</em>.',
    theory: [
      { type: 'rule', title: 'Weather expressions', text: '<em>Il fait</em> + adjective: <em>Il fait beau / froid / chaud</em>. <em>Il pleut</em> (it rains), <em>Il neige</em> (it snows).' },
      { type: 'example', fr: 'Quel temps fait-il aujourd\'hui ?', en: 'What\'s the weather like today?' },
    ],
    words: [
      w('temps', 'weather / time', { article: 'le' }), w('soleil', 'sun', { article: 'le' }),
      w('pluie', 'rain', { article: 'la' }), w('neige', 'snow', { article: 'la' }),
      w('vent', 'wind', { article: 'le' }), w('nuage', 'cloud', { article: 'le' }),
      w('ciel', 'sky', { article: 'le' }), w('mer', 'sea', { article: 'la' }),
      w('montagne', 'mountain', { article: 'la' }), w('rivière', 'river', { article: 'la' }),
      w('forêt', 'forest', { article: 'la' }), w('plage', 'beach', { article: 'la' }),
      w('chaud', 'hot'), w('froid', 'cold'), w('beau', 'nice / beautiful'),
      w('Il fait beau.', 'The weather is nice.'), w('Il pleut.', 'It\'s raining.'),
      w('tempête', 'storm', { article: 'la' }), w('arc-en-ciel', 'rainbow', { article: 'l\'' }),
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Transport',
    frenchLabel: 'Voyage',
    emoji: '✈️',
    accent: 'blue',
    description: 'Airports, trains, tickets, and getting around.',
    theory: [
      { type: 'tip', text: 'Key verbs: <em>partir</em> (leave), <em>arriver</em> (arrive), <em>prendre</em> (take a train/plane), <em>rater</em> (miss a connection).' },
      { type: 'example', fr: 'Où est la gare, s\'il vous plaît ?', en: 'Where is the train station, please?' },
    ],
    words: [
      w('voyage', 'trip', { article: 'le' }), w('vacances', 'holiday', { article: 'les' }),
      w('aéroport', 'airport', { article: 'l\'' }), w('gare', 'train station', { article: 'la' }),
      w('avion', 'plane', { article: 'l\'' }), w('train', 'train', { article: 'le' }),
      w('métro', 'subway', { article: 'le' }), w('bus', 'bus', { article: 'le' }),
      w('taxi', 'taxi', { article: 'le' }), w('voiture', 'car', { article: 'la' }),
      w('vélo', 'bicycle', { article: 'le' }), w('billet', 'ticket', { article: 'le' }),
      w('passeport', 'passport', { article: 'le' }), w('valise', 'suitcase', { article: 'la' }),
      w('hôtel', 'hotel', { article: 'l\'' }), w('réservation', 'reservation', { article: 'la' }),
      w('partir', 'to leave'), w('arriver', 'to arrive'), w('retard', 'delay', { article: 'le' }),
      w('douane', 'customs', { article: 'la' }),
    ],
  },
  {
    id: 'city-directions',
    label: 'City & Directions',
    frenchLabel: 'En ville',
    emoji: '🗺️',
    accent: 'orange',
    description: 'Navigate streets, ask for directions, and find places in town.',
    theory: [
      { type: 'rule', title: 'Asking directions', text: '<em>Où est… ?</em> / <em>Comment aller à… ?</em> Answers use <em>à gauche</em>, <em>à droite</em>, <em>tout droit</em>.' },
      { type: 'example', fr: 'Tournez à droite après la banque.', en: 'Turn right after the bank.' },
    ],
    words: [
      w('ville', 'city', { article: 'la' }), w('rue', 'street', { article: 'la' }),
      w('place', 'square', { article: 'la' }), w('pont', 'bridge', { article: 'le' }),
      w('parc', 'park', { article: 'le' }), w('magasin', 'shop', { article: 'le' }),
      w('banque', 'bank', { article: 'la' }), w('poste', 'post office', { article: 'la' }),
      w('hôpital', 'hospital', { article: 'l\'' }), w('église', 'church', { article: 'l\'' }),
      w('musée', 'museum', { article: 'le' }), w('pharmacie', 'pharmacy', { article: 'la' }),
      w('gauche', 'left'), w('droite', 'right'), w('tout droit', 'straight ahead'),
      w('près de', 'near'), w('loin de', 'far from'), w('à côté de', 'next to'),
      w('devant', 'in front of'), w('derrière', 'behind'), w('coin', 'corner', { article: 'le' }),
    ],
  },
  {
    id: 'shopping-money',
    label: 'Shopping & Money',
    frenchLabel: 'Shopping',
    emoji: '💰',
    accent: 'amber',
    description: 'Prices, payment, and bargaining politely in shops.',
    theory: [
      { type: 'rule', title: 'Prices', text: 'Use comma for decimals in France: <em>9,50 €</em> = nine euros fifty. Say <em>neuf euros cinquante</em>.' },
      { type: 'example', fr: 'C\'est combien ? — C\'est quinze euros.', en: 'How much is it? — It\'s fifteen euros.' },
    ],
    words: [
      w('argent', 'money', { article: 'l\'' }), w('euro', 'euro', { article: 'l\'' }),
      w('centime', 'cent', { article: 'le' }), w('prix', 'price', { article: 'le' }),
      w('cher', 'expensive'), w('bon marché', 'cheap / inexpensive'),
      w('gratuit', 'free'), w('soldes', 'sales', { article: 'les' }),
      w('caisse', 'checkout', { article: 'la' }), w('carte', 'card', { article: 'la' }),
      w('espèces', 'cash', { article: 'les' }), w('monnaie', 'change (coins)', { article: 'la' }),
      w('facture', 'receipt / invoice', { article: 'la' }), w('taille', 'size', { article: 'la' }),
      w('essayer', 'to try on'), w('acheter', 'to buy'), w('vendre', 'to sell'),
      w('C\'est combien ?', 'How much is it?'), w('Je regarde seulement.', 'I\'m just looking.'),
    ],
  },
  {
    id: 'health',
    label: 'Health & Medicine',
    frenchLabel: 'Santé',
    emoji: '🏥',
    accent: 'red',
    description: 'Doctor visits, symptoms, and pharmacy essentials.',
    theory: [
      { type: 'rule', title: 'Feeling unwell', text: '<em>Je suis malade</em> (I\'m sick). <em>J\'ai de la fièvre</em> (I have a fever). <em>Il faut</em> + infinitive = you must / one must.' },
      { type: 'example', fr: 'Je voudrais prendre rendez-vous chez le médecin.', en: 'I\'d like to make a doctor\'s appointment.' },
    ],
    words: [
      w('santé', 'health', { article: 'la' }), w('médecin', 'doctor'), w('hôpital', 'hospital', { article: 'l\'' }),
      w('pharmacie', 'pharmacy', { article: 'la' }), w('médicament', 'medicine', { article: 'le' }),
      w('malade', 'sick'), w('fièvre', 'fever', { article: 'la' }),
      w('rhume', 'cold (illness)', { article: 'le' }), w('tousser', 'to cough'),
      w('douleur', 'pain', { article: 'la' }), w('blessure', 'injury', { article: 'la' }),
      w('allergie', 'allergy', { article: 'l\'' }), w('ordonnance', 'prescription', { article: 'l\'' }),
      w('urgence', 'emergency', { article: 'l\'' }), w('repos', 'rest', { article: 'le' }),
      w('guérir', 'to heal / cure'), w('Je suis malade.', 'I\'m sick.'), w('Appelez une ambulance !', 'Call an ambulance!'),
    ],
  },
  {
    id: 'sports-hobbies',
    label: 'Sports & Hobbies',
    frenchLabel: 'Sports et loisirs',
    emoji: '⚽',
    accent: 'green',
    description: 'Play, watch, and talk about what you love doing in free time.',
    theory: [
      { type: 'rule', title: 'Jouer vs faire', text: '<em>jouer à</em> + sport/game: <em>jouer au football</em>. <em>faire</em> + activity: <em>faire du vélo, de la natation</em>.' },
      { type: 'example', fr: 'Le week-end, je fais de la randonnée.', en: 'On weekends I go hiking.' },
    ],
    words: [
      w('sport', 'sport', { article: 'le' }), w('football', 'football / soccer', { article: 'le' }),
      w('tennis', 'tennis', { article: 'le' }), w('basketball', 'basketball', { article: 'le' }),
      w('natation', 'swimming', { article: 'la' }), w('course', 'running', { article: 'la' }),
      w('vélo', 'cycling', { article: 'le' }), w('musique', 'music', { article: 'la' }),
      w('cinéma', 'cinema', { article: 'le' }), w('lecture', 'reading', { article: 'la' }),
      w('jeu', 'game', { article: 'le' }), w('équipe', 'team', { article: 'l\'' }),
      w('match', 'match / game', { article: 'le' }), w('gagner', 'to win'), w('perdre', 'to lose'),
      w('jouer', 'to play'), w('faire', 'to do / make'), w('passion', 'passion', { article: 'la' }),
      w('loisir', 'leisure', { article: 'le' }), w('collection', 'collection', { article: 'la' }),
    ],
  },
  {
    id: 'emotions',
    label: 'Emotions & Feelings',
    frenchLabel: 'Les émotions',
    emoji: '😊',
    accent: 'pink',
    description: 'Express how you feel — many use <em>avoir</em> instead of <em>être</em>.',
    theory: [
      { type: 'rule', title: 'Avoir + emotion', text: '<em>J\'ai peur</em> (I\'m afraid), <em>J\'ai honte</em> (I\'m ashamed), <em>J\'ai faim/soif</em>. But: <em>Je suis content/triste/fatigué</em>.' },
      { type: 'example', fr: 'Je suis content de te voir !', en: 'I\'m happy to see you!' },
    ],
    words: [
      w('heureux', 'happy (m)'), w('heureuse', 'happy (f)'), w('triste', 'sad'),
      w('content', 'pleased (m)'), w('contente', 'pleased (f)'), w('fâché', 'angry (m)'),
      w('fatigué', 'tired (m)'), w('fatiguée', 'tired (f)'), w('surpris', 'surprised (m)'),
      w('peur', 'fear', { article: 'la' }), w('amour', 'love', { article: 'l\'' }),
      w('joie', 'joy', { article: 'la' }), w('colère', 'anger', { article: 'la' }),
      w('stress', 'stress', { article: 'le' }), w('ennui', 'boredom', { article: 'l\'' }),
      w('J\'ai peur.', 'I\'m afraid.'), w('Je m\'ennuie.', 'I\'m bored.'),
      w('Ça me rend heureux.', 'It makes me happy.'), w('Ne t\'inquiète pas.', 'Don\'t worry.'),
    ],
  },
  {
    id: 'adjectives',
    label: 'Common Adjectives',
    frenchLabel: 'Adjectifs',
    emoji: '✨',
    accent: 'purple',
    description: 'Size, quality, and description — remember BANGS adjectives go before the noun.',
    theory: [
      { type: 'rule', title: 'BANGS', text: 'Beauty, Age, Number, Good/Bad, Size go <strong>before</strong> the noun: <em>une belle maison</em>, <em>un grand homme</em> (great man), <em>un homme grand</em> (tall man).' },
      { type: 'tip', text: 'Most color and nationality adjectives go after: <em>une voiture rouge</em>, <em>un étudiant français</em>.' },
    ],
    words: [
      w('grand', 'big / tall'), w('petit', 'small'), w('gros', 'fat / big'),
      w('long', 'long'), w('court', 'short'), w('large', 'wide'),
      w('beau', 'beautiful (m)'), w('belle', 'beautiful (f)'), w('joli', 'pretty (m)'),
      w('bon', 'good'), w('mauvais', 'bad'), w('meilleur', 'better / best'),
      w('nouveau', 'new (m)'), w('vieux', 'old (m)'), w('jeune', 'young'),
      w('facile', 'easy'), w('difficile', 'difficult'), w('important', 'important'),
      w('intéressant', 'interesting'), w('possible', 'possible'), w('nécessaire', 'necessary'),
      w('vrai', 'true'), w('faux', 'false'),
    ],
  },
  {
    id: 'greetings-basics',
    label: 'Greetings & Basics',
    frenchLabel: 'Salutations',
    emoji: '👋',
    accent: 'teal',
    description: 'Hello, goodbye, please, thank you — the social glue of every conversation.',
    theory: [
      { type: 'rule', title: 'Formality', text: '<em>Bonjour</em> until evening, then <em>Bonsoir</em>. <em>Salut</em> = hi/bye (informal). Always add <em>Monsieur / Madame / Mademoiselle</em> in shops.' },
      { type: 'tip', text: 'The French expect <em>Bonjour</em> before any request — skipping it sounds rude.' },
    ],
    words: [
      w('bonjour', 'hello / good morning'), w('bonsoir', 'good evening'),
      w('salut', 'hi / bye (informal)'), w('au revoir', 'goodbye'),
      w('à bientôt', 'see you soon'), w('à demain', 'see you tomorrow'),
      w('merci', 'thank you'), w('merci beaucoup', 'thank you very much'),
      w('de rien', 'you\'re welcome'), w('s\'il vous plaît', 'please (formal)'),
      w('s\'il te plaît', 'please (informal)'), w('pardon', 'sorry / excuse me'),
      w('excusez-moi', 'excuse me (formal)'), w('enchanté', 'nice to meet you (m)'),
      w('Comment allez-vous ?', 'How are you? (formal)'), w('Ça va ?', 'How\'s it going?'),
      w('Très bien, merci.', 'Very well, thanks.'), w('Oui', 'yes'), w('Non', 'no'),
    ],
  },
  {
    id: 'questions',
    label: 'Question Words',
    frenchLabel: 'Questions',
    emoji: '❓',
    accent: 'blue',
    description: 'Who, what, where, when, why, how — build real questions fast.',
    theory: [
      { type: 'rule', title: 'Three question styles', text: '1) Intonation: <em>Tu viens ?</em> 2) Est-ce que: <em>Est-ce que tu viens ?</em> 3) Inversion: <em>Viens-tu ?</em> (formal/written).' },
      { type: 'example', fr: 'Où est la gare ?', en: 'Where is the station?' },
    ],
    words: [
      w('qui', 'who'), w('que', 'what'), w('quoi', 'what (after prep)'),
      w('où', 'where'), w('quand', 'when'), w('comment', 'how'),
      w('pourquoi', 'why'), w('combien', 'how much / many'),
      w('quel', 'which (m)'), w('quelle', 'which (f)'), w('quels', 'which (m pl)'),
      w('quelles', 'which (f pl)'), w('Est-ce que', 'question marker'),
      w('est-ce que', 'is it that…'), w('Qui est-ce ?', 'Who is it?'),
      w('Qu\'est-ce que c\'est ?', 'What is it?'), w('Pourquoi pas ?', 'Why not?'),
    ],
  },
  {
    id: 'prepositions',
    label: 'Prepositions',
    frenchLabel: 'Prépositions',
    emoji: '🔗',
    accent: 'orange',
    description: 'In, on, at, to, from — and the contractions that trip everyone up.',
    theory: [
      { type: 'rule', title: 'Contractions', text: '<em>à + le = au</em>, <em>à + les = aux</em>, <em>de + le = du</em>, <em>de + les = des</em> (partitive). <em>à la, de la, de l\'</em> stay separate.' },
      { type: 'example', fr: 'Je vais au cinéma avec mes amis.', en: 'I\'m going to the cinema with my friends.' },
    ],
    words: [
      w('à', 'to / at'), w('de', 'of / from'), w('en', 'in (countries) / by (transport)'),
      w('dans', 'in / inside'), w('sur', 'on'), w('sous', 'under'),
      w('avec', 'with'), w('sans', 'without'), w('pour', 'for'),
      w('par', 'by / through'), w('chez', 'at someone\'s place'),
      w('entre', 'between'), w('devant', 'in front of'), w('derrière', 'behind'),
      w('près de', 'near'), w('loin de', 'far from'), w('à côté de', 'next to'),
      w('au', 'to the / at the (m)'), w('du', 'some / of the (m)'), w('aux', 'to the (pl)'),
    ],
  },
  {
    id: 'common-verbs',
    label: 'Common Verbs',
    frenchLabel: 'Verbes essentiels',
    emoji: '🏃',
    accent: 'green',
    description: 'High-frequency verbs every learner needs in present tense.',
    theory: [
      { type: 'rule', title: 'Present patterns', text: '-ER: <em>parler → je parle</em>. -IR (type 2): <em>finir → je finis</em>. Irregulars: <em>être, avoir, aller, faire</em> — drill these daily.' },
      { type: 'tip', text: 'French never drops the subject pronoun — always say <em>je, tu, il…</em>' },
    ],
    words: [
      w('être', 'to be'), w('avoir', 'to have'), w('aller', 'to go'),
      w('faire', 'to do / make'), w('pouvoir', 'can / to be able'),
      w('vouloir', 'to want'), w('devoir', 'must / to have to'),
      w('savoir', 'to know (fact)'), w('connaître', 'to know (person/place)'),
      w('parler', 'to speak'), w('manger', 'to eat'), w('boire', 'to drink'),
      w('dormir', 'to sleep'), w('travailler', 'to work'), w('étudier', 'to study'),
      w('aimer', 'to like / love'), w('prendre', 'to take'), w('venir', 'to come'),
      w('voir', 'to see'), w('dire', 'to say'), w('mettre', 'to put'),
      w('comprendre', 'to understand'), w('apprendre', 'to learn'),
    ],
  },
  {
    id: 'technology',
    label: 'Technology',
    frenchLabel: 'Technologie',
    emoji: '💻',
    accent: 'blue',
    description: 'Devices, internet, and modern digital life vocabulary.',
    theory: [
      { type: 'tip', text: 'Many tech words are borrowed: <em>le wifi</em>, <em>le smartphone</em>, <em>le streaming</em>. Verbs: <em>télécharger</em> (download), <em>se connecter</em> (log in).' },
    ],
    words: [
      w('ordinateur', 'computer', { article: 'l\'' }), w('téléphone', 'phone', { article: 'le' }),
      w('portable', 'laptop / mobile', { article: 'le' }), w('écran', 'screen', { article: 'l\'' }),
      w('clavier', 'keyboard', { article: 'le' }), w('souris', 'mouse', { article: 'la' }),
      w('internet', 'internet', { article: 'l\'' }), w('site', 'website', { article: 'le' }),
      w('application', 'app', { article: 'l\'' }), w('mot de passe', 'password', { article: 'le' }),
      w('courriel', 'email', { article: 'le' }), w('message', 'message', { article: 'le' }),
      w('photo', 'photo', { article: 'la' }), w('vidéo', 'video', { article: 'la' }),
      w('télécharger', 'to download'), w('envoyer', 'to send'), w('recevoir', 'to receive'),
      w('connecter', 'to connect'), w('imprimer', 'to print'),
    ],
  },
  {
    id: 'arts-music',
    label: 'Arts & Music',
    frenchLabel: 'Arts et musique',
    emoji: '🎭',
    accent: 'pink',
    description: 'Culture, creativity, and entertainment vocabulary.',
    theory: [
      { type: 'example', fr: 'Tu veux aller au concert ce soir ?', en: 'Do you want to go to the concert tonight?' },
    ],
    words: [
      w('art', 'art', { article: 'l\'' }), w('musique', 'music', { article: 'la' }),
      w('chanson', 'song', { article: 'la' }), w('film', 'film', { article: 'le' }),
      w('théâtre', 'theatre', { article: 'le' }), w('concert', 'concert', { article: 'le' }),
      w('peinture', 'painting', { article: 'la' }), w('photo', 'photography', { article: 'la' }),
      w('danse', 'dance', { article: 'la' }), w('livre', 'book', { article: 'le' }),
      w('roman', 'novel', { article: 'le' }), w('poème', 'poem', { article: 'le' }),
      w('artiste', 'artist'), w('acteur', 'actor (m)'), w('actrice', 'actress'),
      w('chanter', 'to sing'), w('danser', 'to dance'), w('dessiner', 'to draw'),
      w('jouer', 'to play (instrument)'), w('écouter', 'to listen'), w('regarder', 'to watch'),
    ],
  },
  {
    id: 'countries-languages',
    label: 'Countries & Languages',
    frenchLabel: 'Pays et langues',
    emoji: '🌍',
    accent: 'teal',
    description: 'Nationalities, languages, and talking about where you\'re from.',
    theory: [
      { type: 'rule', title: 'En vs Au', text: 'Feminine countries: <em>en France, en Italie</em>. Masculine: <em>au Japon, au Canada</em>. Vowel: <em>en Iran</em>. Plural: <em>aux États-Unis</em>.' },
      { type: 'rule', title: 'Nationalities', text: 'Lowercase, agree with person: <em>un Français, une Française, des Américains</em>.' },
    ],
    words: [
      w('pays', 'country', { article: 'le' }), w('France', 'France'), w('Angleterre', 'England'),
      w('États-Unis', 'United States'), w('Canada', 'Canada'), w('Allemagne', 'Germany'),
      w('Espagne', 'Spain'), w('Italie', 'Italy'), w('Japon', 'Japan'), w('Russie', 'Russia'),
      w('français', 'French (m)'), w('française', 'French (f)'), w('anglais', 'English (m)'),
      w('anglaise', 'English (f)'), w('langue', 'language', { article: 'la' }),
      w('nationalité', 'nationality', { article: 'la' }), w('Je suis de…', 'I am from…'),
      w('Je parle…', 'I speak…'), w('étranger', 'foreigner (m)'), w('monde', 'world', { article: 'le' }),
    ],
  },
  {
    id: 'time-expressions',
    label: 'Time Expressions',
    frenchLabel: 'Expressions de temps',
    emoji: '⏰',
    accent: 'amber',
    description: 'Always, never, sometimes — adverbs that shape when things happen.',
    theory: [
      { type: 'rule', title: 'Placement', text: 'Short adverbs often go after the verb: <em>Je mange souvent ici</em>. Longer ones at start/end: <em>Parfois, je travaille le dimanche</em>.' },
      { type: 'example', fr: 'Je ne suis jamais en retard.', en: 'I am never late.' },
    ],
    words: [
      w('maintenant', 'now'), w('tout de suite', 'right away'), w('bientôt', 'soon'),
      w('déjà', 'already'), w('encore', 'still / again'), w('toujours', 'always'),
      w('jamais', 'never'), w('souvent', 'often'), w('parfois', 'sometimes'),
      w('rarement', 'rarely'), w('quelquefois', 'sometimes'), w('longtemps', 'a long time'),
      w('pendant', 'during'), w('depuis', 'since / for'), w('jusqu\'à', 'until'),
      w('avant', 'before'), w('après', 'after'), w('pendant', 'during'),
      w('tôt', 'early'), w('tard', 'late'), w('d\'habitude', 'usually'),
    ],
  },
];
